### ISSUE TITLE
Nested poppers in separate DOM contexts not updating position

### ISSUE THREAD

**Issue by zbrogz** [floating-ui/floating-ui#1267]
### CodeSandbox demo

https://codesandbox.io/s/practical-jepsen-lw8s9

### Steps to reproduce the problem

1. Scroll down to the first reference element, "menuAnchor"
2. Click on "menuAnchor" to open the first popper
3. Click on "subMenuAnchor" to open the next popper
4. Scroll the page and the nested popper's position does not update with it's reference element ("subMenuAnchor")

### What is the expected behavior?

The nested poppers' position should update with the reference element as the page is scrolled.

### What went wrong?

Removing position: absolute or overflow: scroll from the parent div is a workaround.

### Any other comments?

Original `react-popper` issue: https://github.com/popperjs/react-popper/issues/412

![Kapture 2021-03-24 at 17 39 47](https://user-images.githubusercontent.com/319162/112519852-61ac7100-8d60-11eb-84bc-3c1422ffc190.gif)

### Package versions
@popperjs/core: 2.9.1

**Comment by FezVrasta** [comment]
It looks like we are forgetting to add an event listener on the container. If you resize the page when the two menus detach they get reattached properly.

**Comment by zbrogz** [comment]
> It looks like we are forgetting to add an event listener on the container

Yes, that appears to be the issue. Only the first popper is adding a scroll event listener to the container `div` element.

**Comment by far-fetched** [comment]
Hey, is there any progress with this issue? @zbrogz Do you have working solution ?

**Comment by zbrogz** [comment]
Sorry, no progress on my end.

**Comment by achambers** [comment]
Hi @FezVrasta . Any chance you might be able to give us some indication as to whether this is something on the team's radar to fix any time soon?

If not, is someone here able to give us a steer on where we might start focusing our efforts if we were to provide a PR to fix this ourselves?

**Comment by FezVrasta** [comment]
What @zbrogz outlined is the most likely cause, one should understand why the function is not returning all the relevant scroll parents and fix it.

If somebody created a PR with a failing test it could be used to help others write a solution.

**Comment by phungleson** [comment]
Hey, I also ran into the same issue.

My guess is that the reference of the second popover is not child of the first reference (which is the child of the scrollable area). That's why when we query scroll parent for the second reference it doesn't return the first scrollable area, so when the first scrollable area changes, it doesn't update position of the second popover.

Hopefully it sheds some light into the solution.

**Comment by far-fetched** [comment]
Yep, you are right 💯 !
Clarification maybe for anyone who has similar problem:
It turns out, that in our case is enough that the second popper would be the child of the first one. Then when popper updates position of first - at the same time it updates second popper (this which is included as child) <--- that was a workaround for this issue for me.

**Comment by phungleson** [comment]
For people searching for solution, I managed to make this work by providing a custom modifier.

Where you have to calculate the `parents` for the first reference yourself and provide to the modifier.

```
{
  name: 'externalScroll',
  options: {
    parents,
  },
  enabled: true,
  phase: 'write',
  fn: () => {
    //
  },
  effect: ({ instance, options }: ModifierArguments<Options>) => {
    const parents = options.parents as Parent[];

    parents?.forEach(parent => {
      parent.addEventListener('scroll', instance.update, { passive: true });
    });

    return () => {
      parents?.forEach(parent => {
        parent.removeEventListener('scroll', instance.update);
      });
    };
  },
}
```

**Comment by atomiks** [comment]
This seems like a tricky problem and actually exposes that `scrollParent` isn't sufficient to detect elements that need a listener attached.

Since the `subMenuAnchor` button is inside the popper, which is not a child of the scrollable container, it doesn't list `.container` as a scrollParent. This means the concept of `scrollParent` is actually flawed, since it doesn't cover this case; probably needs to be `scrollLink` or such in this case. Not sure how this can be done 🤔  the manual solution listed by @phungleson will work for any case, but it makes it less "automagic"

**Comment by atomiks** [comment]
Hi, we're closing all feature requests related to Popper as it is entering low maintenance mode. All feature requests should now relate to the new package, [Floating UI](https://floating-ui.com)!

**Comment by Siva2908** [comment]
for a work around, you may toggle hide style properties when the first element property gets changed.
