### ISSUE TITLE
Update the width of the floating through prop

### ISSUE THREAD

**Issue by tounsoo** [floating-ui/floating-ui#1505]
Since I'm using `React-dom` version, I had to created a different CSB.

## Situation
Trying to solve a use case where popover changes size when user clicks a particular button.

## How I would like it to work
There is a Popover component using floating-ui/react-dom. When someone is using Popover component and passes a new width value to the `width` prop, I want the `update` to fire so it gets the new width.

## CodeSandbox
https://codesandbox.io/s/vibrant-water-zpyem?file=/src/popover.js

**Comment by atomiks** [comment]
This is an interesting case where stringifying the function to check if `middleware` changed in our `deepEqual` util won't work since it's referring to a variable which changes at runtime and can't be statically analyzed.

What I'd do here is avoid using `size`, just pass the `width` to the element and call `update` when it changes: https://codesandbox.io/s/determined-fast-2bd01?file=/src/popover.js

**Comment by tounsoo** [comment]
Cool, I updated the [CodeSandbox](https://codesandbox.io/s/vibrant-water-zpyem?file=/src/popover.js) to test if it would work well with the `getScrollParents` and it works nicely! Thank you :D
