### ISSUE TITLE
Unclear usage of sizing middleware with react.

### ISSUE THREAD

**Issue by janwirth** [floating-ui/floating-ui#1512]
https://codesandbox.io/s/vibrant-williamson-bx77n?file=/src/App.tsx

I'm trying to get sizing middleware to work with react. I am getting incorrect behavior and weird values in console.log output. Thanks

**Comment by atomiks** [comment]
https://github.com/floating-ui/floating-ui/issues/1445

**Comment by janwirth** [comment]
Thanks, that solves part of the problem. I also needed to use the correct property in my styles object:

```tsx
{maxWidth: sizeData?.reference.width ?? ""}
```

Working example is here now: https://codesandbox.io/s/vibrant-williamson-bx77n?file=/src/App.tsx

Feel free to use it to improve documentation.

**Comment by janwirth** [comment]
@atomiks thank you for your help, I think the behavior is still incorrect. The sizing works now correctly, but when I scroll the container it's not updating the position. What am I missing?

https://codesandbox.io/s/vibrant-williamson-bx77n?file=/src/App.tsx

**Comment by atomiks** [comment]
Floating UI is lower level than Popper, enabling full control. You want to read these:

- https://floating-ui.com/docs/react-dom#updating
- https://floating-ui.com/docs/computePosition#updating

**Comment by atomiks** [comment]
Working example: https://codesandbox.io/s/exciting-poincare-ghkyn?file=/src/App.tsx (you'll want to call update whenever `isOpen` changes too since you're not conditionally rendering the floating element, where a `ref` change would handle that automatically.)

Something weird I noticed is that the `reference` has a width of 57.?px on the first render (inside `useLayoutEffect`) unexpectedly. 

If you use `style={{width: '100%'}}` instead of `w-full` there's no problem, so it kinda looks like Tailwind's JIT thing is buggy and not working before the first render phase.

**Comment by atomiks** [comment]
⚠️ ⚠️ ⚠️ ⚠️ !

This is no longer recommended for React 18 as it's buggy. Instead, just mutate the style directly (more performant also).

Use the `refs` object that gets returned:

```js
  const {x, y, reference, floating, strategy, update, refs} = useFloating({
    placement,
    middleware: [
      size({
        apply({width, height}) {
          if (!refs.floating.current) return;

          Object.assign(refs.floating.current.style, {
            maxWidth: `${width}px`,
            maxHeight: `${height}px`,
          });
        },
        padding: 10,
      }),
    ],
  });
```
