### ISSUE TITLE
Where are the v1 examples?

### ISSUE THREAD

**Issue by dilyanpalauzov** [floating-ui/floating-ui#1513]
The v1.x branch has under doc/ an index.html file.  This file includes e.g. `_includes/example10.html`.

Where can I find online the rendering of doc/index.html with the examples?  https://popper.js.org/docs/v1/ does not show it.

**Comment by atomiks** [comment]
The new Popper website we made for v2 didn't port the v1.x examples over, just the main documentation. That code is heavily legacy and will never be rendered on the site, not to mention v1.x hasn't been updated since 2019 and is deprecated, so I'm not sure why you're using it? I can only think of Bootstrap 4, but I don't think you'd be using Popper directly?

**Comment by dilyanpalauzov** [comment]
Yes, the keyword is Bootstrap 4.  In fact I am using an utterly old code written for IE6 and I want to migrate it to Popper js v1, as I use Bootstrap 4 anyway.  So I want to remove the utterly old code for showing popups.

**Comment by atomiks** [comment]
If you use Popper.js v1 you'll be going from ancient code to old code 😉 

I would just use Bootstrap 4's tooltip/popover/dropdown components rather than positioning custom popups yourself.

If you really want to start fresh, use Floating UI and don't include Popper (if you're not using Boostrap's components), because that's the future of this project.
