### ISSUE TITLE
Popper positioning problem when multiple relative parents

### ISSUE THREAD

**Issue by Creatium** [floating-ui/floating-ui#1527]
Hi. I am copying my problem query here from StackOverflow, because I did not receive any help there. Hopefully my cries could be answered here. Original question: https://stackoverflow.com/questions/70914938/popper-positioning-problem-when-multiple-relative-parents

I'm trying to implement Popper JS library for use in my situation (eventually creating a dropdown menu). The problem I am having is when Popper elements (button and tooltip) are placed inside at least two-levels parents, the top one being absolutely positioned and using overflow: auto, the Popper is not popping outside all the elements.

Here is a Codepen: https://codepen.io/meexo/pen/BamoGwv

In this example you will see that on button mouseenter Popper is appearing inside elements and Overflow is getting scroll. But if you remove one parent level (i.e. "row" class element), Popper appears outside element as it should be.

And here is the simplest code:

HTML:

```
<div class="parent">
  <div class="row"> <!-- remove this level and it works -->
    <div class="popover-parent">
      <button class="popover">Custom popover 2</button>
      <span class="popover-content content-2">Content for the second popover</span>
    </div>
  </div>
</div>
```

CSS:

```
.parent {
  position: absolute;
  top: 20px;
  border: 1px solid black;
  overflow: auto;
}

.popover-parent {
/*   position: relative; */
}

.popover-content {
  display: none;
}

.popover-content[show-popper] {
  display: block;
}
```

JS:

```
var popperInstances = {};

jQuery('.popover-parent').each((index, elm) => {
    let button = jQuery(elm).find('.popover');
    let tooltip = jQuery(elm).find('.popover-content');

    popperInstances[index] = Popper.createPopper(button[0], tooltip[0], {
        placement: 'right',
    });

    button.on('mouseenter', () => {
        tooltip.attr('show-popper', '');

        popperInstances[index].update();
    });

    button.on('mouseleave', () => {
        tooltip.removeAttr('show-popper');
    });
});
```

So what am I missing? Documentation is a bit hard to understand for me. Was trying to look at "preventOverflow" modifier, but basic trials gave no results.

P.S. My code is a bit more complex, but just because I am trying to make it work with multiple elements.

**Comment by atomiks** [comment]
You've got some DOM hierarchy issues going on; the `.parent` element has `position: absolute` AND `overflow` styles, so it becomes a "clipping container". This means the popper can't be shown outside of it when it's a child of it using the `absolute` positioning strategy. 

If you remove the `position: absolute` CSS from the `.parent` and then hover over the button you'll see what I mean.

You've got two choices:

- Use `strategy: 'fixed'` in `createPopper()` which allows the popper to break out of the clipping context and be shown over it. (If you decide to add `will-change` or `transform` on the parent, then this also won't work because it then becomes a "containing block").
- Move the popper outside of the `.parent` hierarchy so it can't be clipped.
