### ISSUE TITLE
Consider RTL directions with the `placement` option

### ISSUE THREAD

**Issue by MuhammadSawalhy** [floating-ui/floating-ui#1530]
CSS has something called [logical propertied](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties), which introduces `block` and `inline` _" to control layout through logical, rather than physical, direction and dimension mappings."_

Also when I set `display: flex` to a DOM element it tidies its children elements respecting the direction of writing which can be set with CSS's `direction: rtl` or the HTML's `dir=rtl` attribute to any tag.

Now I used Floating UI to compute the position of the floating menu that is opened by clicking a button. This floating menu's placement should be either `bottom-end` or `bottom-start` considering the direction of writing which may be RTL. **BUT THIS DOESN'T HAPPEN.**

![image](https://user-images.githubusercontent.com/42011920/152695609-3039ad2f-4956-4b7f-bf06-926898dc0d04.png)

In the above image, the menu has a placement of `bottom-end` but with RTL in our perception this is wrong, it is actually `bottom-start`.

![image](https://user-images.githubusercontent.com/42011920/152695749-97d66ec5-3dc7-480d-b74d-fc2f64b08dd6.png)

With LTR it is just fine :ok_hand:.

**Comment by MuhammadSawalhy** [comment]
A workaround now

```jsx
  const { i18n } = useTranslation();
  const {
    x,
    y,
    reference, // Ref of the floating reference
    floating: menuRef, // the Ref of the floating menu itslef
    strategy: position,
    update,
    refs
  } = useFloating({
    placement: `bottom-${
      i18n.dir() === "rtl" // flip directions when "rtl"
        ? truncateFrom === "start"
          ? "end"
          : "start"
        : truncateFrom
    }`,
    middleware: [offset(5), shift({ padding: 5 })]
  });

```

**Comment by atomiks** [comment]
Do you think it's a good idea to automatically infer the alignment from `direction` style on the floating's parent element? A bit concerned there may be some unwanted side effects if we go down this path.  But the `start` and `end` were designed to eventually handle RTL properly. Your workaround is the common method to swap them.

**Comment by MuhammadSawalhy** [comment]
You can make this behaviour optional. Fo example:

```js
  useFloating({
    placement: `bottom-${truncateFrom}`,
    logicalDirection: true, // 👈 
    middleware: [offset(5), shift({ padding: 5 })]
  });
```

**Comment by atomiks** [comment]
> It is also misleading to use the logical terms start and end which I thought would be analogous to the CSS logical properties

I think it should just be default due to this + I'd rather avoid adding a new option. If they want to "undo" this for whatever reason, they can use your swapping method (meaning they'd use a conditional just like you need to now)

**Comment by FezVrasta** [comment]
Would a middleware make sense?

```js
  useFloating({
    placement: 'bottom-end',
    middleware: [rtlSupport(), offset(5), shift({ padding: 5 })]
  });
```

**Comment by atomiks** [comment]
I think it should be default because `-start` and `-end` imply logical properties, not directional (like `bottom-right` or `bottom-left` would). It's not difficult to undo if this is not desired. 

If a dev is setting `dir="rtl"` (what our check would use) they presumably would want the alignment to change. This is a breaking change v0 is good to do it 🥳

**Comment by WickyNilliams** [comment]
Glad to see this is being considered! 

For full multi-language support you should also not use terms like bottom/top, as they are flipped in vertical languages. I would recommend aligning with css logical properties and using `(block|inline)-(start|end)`, which are entirely independent of horizontal _and_ vertical direction

**Comment by WickyNilliams** [comment]
i think another workaround is something like this:

```ts
computePosition(button, tooltip, {
  placement: "left",
}).then(({x, y}) => {
  // use logical properties
  Object.assign(tooltip.style, {
    insetInlineStart: `${x}px`,
    insetBlockStart: `${y}px`,
  });
});
```

which _should_ do the right thing of positioning to left in LTR and right in RTL... so i'm not sure you'd need to inspect `dir` attributes, or change any internals, except the `placement` names. and of course update docs to use this throughout!

**Comment by MuhammadSawalhy** [comment]
> you should also not use terms like bottom/top

What about include both groups of positioning, the directional and the logical?! 🤔 So `bottom-end` and `start-left` will be vaild. I don't understand the low-level work of the library but a middleware may be good to accomplish this, whuch will detect the writing direction and mode to trnaslate the logical `start` and `end` to directional `bottom`, `top`, `left`, `right`

**Comment by MuhammadSawalhy** [comment]
> i think another workaround is something like this

Unfortunately not working

**Comment by WickyNilliams** [comment]
I  think it would be best to align with the css logical properties only rather than support both. IMO in the near future everyone will write their css with logical properties only, since they give you so much for free. So it would be best to get ahead of the curve and start using them from the beginning

**Comment by atomiks** [comment]
A couple of concerns:

1. `{block|inline}-{start|end}` is foreign to most devs right now; logical properties are way less intuitive than physical ones. 
2. We can't specify an alignment. This may mean we need to split this into two separate options.

For example, `block-start` for English is the `top` side. But that will just use the center alignment. `block-start-start` is weird syntax.

`top-end` right now would be:

```js
side: 'block-start',
align: 'end',
```

Thinking we should actually forgo `start` and `end` and use physical properties by default and make `logicalProperties` a middleware which enables this behavior?

**Comment by WickyNilliams** [comment]
Yeah I agree they are a little less intuitive, but not a great deal. More verbose though, for sure. 

However, I still personally think this should be first class, not opt in with middleware. You could view it as a selling/marketing point: "supports RTL out of the box"!

You're absolutely right about it needing two properties if this were the case

**Comment by atomiks** [comment]
Starting with a physical side and then using a logical alignment is really intuitive imo (the current API). 

You avoid having to think about the direction of the alignment, for example `top-right` and `right-top` describe `top-end` and `right-start` in the current API but the latter is less confusing to me. I think handling the alignment with RTL is far more common than needing to handle writing mode directions.
 
I'm thinking we should support RTL by default and keep the current placement option. Handling writing modes is something the user could do themselves if needed as a middleware, because it really is an advanced use case and requires a big change to the placement options by splitting them into two.

**Comment by atomiks** [comment]
I made an umbrella issue here to get these changes in for v1: https://github.com/floating-ui/floating-ui/issues/1538

**Comment by driskull** [comment]
Hello, I see that `*-start` and `*-end` are now flipped when the direction is RTL.

Will there be an equivalent to flip `left/right` as well? Will there be `block-end` and `inline-start`? so that the first part is also flipped in RTL?

For example, `right-end` only flips the `-end` part in RTL, not the `right`.

**Comment by atomiks** [comment]
@driskull tracking it here https://github.com/floating-ui/floating-ui/issues/1563

**Comment by atomiks** [comment]
^ The main issue there is supporting things like CSS `writing-mode` & `text-orientation` which massively increases complexity. Supporting just `direction` (and therefore RTL) only is not too hard and we already have a method for that. Since the former two properties are kind of obscure compared to `direction`, not sure if we should bother supporting them logically
