### ISSUE TITLE
[Core] Logical side placements

### ISSUE THREAD

**Issue by ling1726** [floating-ui/floating-ui#1563]
I see that alignment has first class support for RTL: https://github.com/floating-ui/floating-ui/blob/a8de472098fdae2e7b45353402f56ae249a9d906/packages/core/src/computeCoordsFromPlacement.ts#L38-L45

Should this also be done for the side ? i.e. `left` becomes `right` and vice versa. I can't speak for all users of the library but we are currently switching the side placement for rtl handling always. Is this a valid scenario for floating ui ?

**Comment by atomiks** [comment]
Decided to leave `side` physical for these reasons here: https://github.com/floating-ui/floating-ui/discussions/1549

You'd can something like:

```js
computePosition(a, b, {
  // right for LTR, left for RTL
  placement: logical('inline-end', isRTL(b)),
});
```

We could technically export this

**Comment by ling1726** [comment]
Yeah that function is very similar to something we wrote for Popper (we also mapped a our own placement terms, but the rtl handling is similar to what you're proposing)

https://github.com/microsoft/fluentui/blob/63447028978db5e34dc46d56fb63fd02290a44b5/packages/react-positioning/src/utils/positioningHelper.ts#L32

Previously  when we used popper we would pass the the RTL down from React context (since we used React), so definitely more used to explicitly configuring this.

However, after testing the computed position, it seems that `dir` also cascades down the DOM tree so I'm not against this.

**Comment by atomiks** [comment]
Later on we can export a logical -> physical side/placement converter but for now it's not crucial. An issue can be opened to track that feature if it's requested frequently.

**Comment by atomiks** [comment]
Reopening because this is kinda bothering me leading up to v1 given it's a breaking change. 😅 I feel like it should be supported by default with space-separated syntax (like CSS). I hope it's not too costly to support by default though. I'll investigate, but at minimum I think it should be supported via an export as mentioned, though built-in would be better.

e.g.
`placement: 'inline-start end`

**Comment by atomiks** [comment]
After experimenting with how this would work I think it's sort of impractical to do built-in:

- `writing-mode` is obscure but necessary for this feature to make any real sense. But it adds a lot to the bundle size.
- If we don't add `writing-mode`, then `block-*` logical sides are useless, because only `inline-*` sides have effect in RTL mode.
- Logical alignments made much more sense than logical sides in terms of ergonomics because they are always the same unlike physical alignments which are different depending on the side, e.g. `top` alignment only makes sense for `left`/`right` sides.
- A lot of edge cases to consider
- A physical function can still do this work.

I don't think it should block v1.
