### ISSUE TITLE
`inline` middleware cannot use with `size`

### ISSUE THREAD

**Issue by gavinxgu** [floating-ui/floating-ui#1570]
## Problem

When using `floating-ui/dom` 0.3, `inline` middleware cannot use with `size`,  but 0.2 this can be achieved.

## CodeSandbox

https://codesandbox.io/s/floating-ui-dom-template-forked-fmq4wr?file=/src/index.js

## Codebase

`inline` middleware changed the reference rect, but  `inline` middleware reset it back

https://github.com/floating-ui/floating-ui/blob/51678336acd05a4d30fa16ca4699d1a8c068e855/packages/core/src/middleware/size.ts#L82-L86

**Comment by gavinxgu** [comment]
@alexdilley Thanks for the work, but I think the problem still exists.

- `inline`
- reset: rects（reference rect resets to one of the multi-line rects）
-  size
- `inline`
- reset: rects（reference rect resets to boundingClientRect)
- wrong result

Maybe we should only reset floating rect in `size` middleware.

**Comment by atomiks** [comment]
Nah it does fix the issue. `inline` just has to run twice, with one of the runs occuring after the `size` reset, which is how it worked before. 

I've removed skipping entirely in a separate commit entirely because it causes issues and was only there to improve perf (as it's basically cache invalidation problem lol)

**Comment by gavinxgu** [comment]
Oh, I see, I just run as:

- `inline`
- ...other middlewares
- `size`
- `inline`
- ...other middlewares

Then the reference rect will be correct.
