### ISSUE TITLE
Oldest supported typescript version and validation

### ISSUE THREAD

**Issue by ling1726** [floating-ui/floating-ui#1584]
I see that the repo is using a pretty recent version of typescript https://github.com/floating-ui/floating-ui/blob/8e045ef7efffbaea926e4be508b67b9404c8376d/package.json#L47

While I don't think it's necessary to go too far back the typescript versions. It would be good to make a clear expectation of supported typescript versions, since typescript doesn't actually follow semver and tend to make breaking changes in minor versions pretty often.

We still have some requirement to support typescript 3.8 so template literal types are going to be hard for us. Downlevel transpilation would be nice, but even I see that 3.8 is a bit of a stretch, so don't sweat too much about it.

If needed, we have some experience writing tests to check typescript compatibility in a pretty easy way, and would love to contribute to that to floating ui if you'd like

**Comment by shawngustaw** [comment]
@ling1726 I also hit this because we're a bit out of date and ended up solving it by using [patch-package](https://github.com/ds300/patch-package). Just install floating ui like you regularly would and then go into `node_modules/@floating-ui/core/src/types.d.ts` and make this change:

```
-export declare type AlignedPlacement = `${Side}-${Alignment}`;
+export declare type AlignedPlacement = 'top-start' | 'top-end' | 'right-start' | 'right-end' | 'bottom-start' | 'bottom-end' | 'left-start' | 'left-end';
```

then you can run `npx patch-package @floating-ui/core`, commit the `patches` folder into git and then add `"postinstall": "patch-package"` to your package.json's scripts, that way anytime you `npm i` it'll overwrite the template literal types with the hardcoded version. 

Hope it helps!

**Comment by ling1726** [comment]
yeah I'm not discounting patch-package, this issue is rather if the maintainers should set clear expectations with typescript. As I said I'd be happy to contribute validation for the floating-ui for different typescript versions if needed

**Comment by atomiks** [comment]
Template literal types were introduced in late 2020 which was a fair while ago. For this library I just went "full modern" and did everything as evergreen as possible because it's brand new. So in that sense, I guess 4.5 is the minimum? 😅

**Comment by shawngustaw** [comment]
Template literal types were added in 4.1 so that's the true minimum. I get that even that is pretty old so the `patch-package` workaround is an ok compromise imo.

**Comment by ling1726** [comment]
Yeah that's fair @atomiks  

Would you see any value in adding typescript validation to floating-ui, for when typescript releases future versions and the library itself is bumped

**Comment by atomiks** [comment]
If you think it has value for TS users of the library then sure

**Comment by layershifter** [comment]
> Template literal types were introduced in late 2020 which was a fair while ago. For this library I just went "full modern" and did everything as evergreen as possible because it's brand new. So in that sense, I guess 4.5 is the minimum? 😅

To provide you some context we are trying to switch to Floating UI in https://github.com/microsoft/fluentui/pull/21828, _that's why you have so many issues from @ling1726_ 😅 As was mentioned we still have customers (_well, single customer AFAIK_) with TS 3.8 where template literals are not the thing ☹️ 

As a maintainer of UI library I would like to avoid _"solutions"_ (https://github.com/microsoft/fluentui/pull/21828/commits/8e25099c877888cf77f4a900a103b00539d7aa4c) with copying type files to the library. However, **totally agree** about template literals, it's really old feature 👌

We should not stop the community from writing better code only because of that, but it would be great to avoid issues like that https://github.com/facebook/docusaurus/issues/6719. 

_Why it's a problem at all?_ Once a feature from upcoming TS 4.6/4.7/4.8 will be used it will be a **breaking change** for people who are still on TS 4.5. As TypeScript upgrades are usually not trivial and connected with upgrades of underlaying tooling (`ts-jest`, `@typescript-eslint/parser`, etc.) it can stop people from adopting new versions of library only because of typings 🙃 While `patch-package` / `yarn patch` are still options it does not scale well when you need to deliver it to thousands of customers.

The ideal solution from our POV is fix a minbar version of TS and keep it until next major release. You can freely use newer versions of TS in the repo itself with some testing around it, for example, [ts-minbar-test-react-components](https://github.com/microsoft/fluentui/tree/master/apps/ts-minbar-test-react-components).

I checked and the minimal version that currently compiles typings is 4.1. AFAIK the single type that use template literals is `AlignedPlacement`:

![image](https://user-images.githubusercontent.com/14183168/158982475-26a4faab-8b90-4a22-8b1e-7e353d097757.png)

But obviously I can't force you to support TS 3.8 😄 If we can set 4.1 as the requirement it would be really great for us.

**Comment by atomiks** [comment]
4.1 is fine 👍
