### ISSUE TITLE
[Core] `autoPlacement()` should check for space along the `crossAxis`

### ISSUE THREAD

**Issue by jnhooper** [floating-ui/floating-ui#1636]
👋 Hi! I just started using this library and so far everything is going amazing with _one_ small edge case that i've been trying to figure out for a while now.
If you make the window _very_ short (like 200 px tall) the floating bubble sticks to the top or bottom of the window when using autoplacement. I am stuck trying to figure out what's could be causing this, however, it only appears to happen when there is not enough space on the top or bottom of the button reference. In the code pen linked below i've changed the css selector for .App to have a text-align: left instead of the center present in your original demo. switching it back to center appears to fix the issue.

steps to reproduce
1. https://codesandbox.io/s/trusting-gauss-9w4s5x?file=/src/App.tsx
2. make your window very short, around 200-400 px (the issue gets worse at shorter sizes for some reason. around 400 px it "fixes itself" eventually and the toolthip dissapears from the screen)
3. scroll down and open the dialog with the "i stick" button.

https://user-images.githubusercontent.com/8321632/163896737-5b11b3b3-8c45-4ee2-815a-a3fd63a92260.mov

**Comment by atomiks** [comment]
I think in this case you want `shift()` to be placed _before_ `autoPlacement()` in the array, so that the algorithm knows it has enough space (it overflows the left side, but shift will prevent that, hinting that it can be placed there).

Further, `shift` causes it to "stick" by default, but this can be prevented via a limiter: https://floating-ui.com/docs/shift#limiter

**Comment by atomiks** [comment]
Looked at this again. 

A combination of `shift()` being placed before `autoPlacement()` AND a `limiter` being given to `shift` fixes the problem in a more desirable way (but I still wouldn't say optimal).

The reason is `autoPlacement()` only checks for space along the `mainAxis` (can't be configured), which is the axis that runs along the `side` of the floating element (for `right` that's `x`). 

In this case you probably want to use `flip()` instead because it can check both axes. I removed `autoPlacement()` checking both axes because there was a problem with doing that sometimes because of the fact it checks for "most space", unlike `flip` which checks for "no space".

Perhaps we can instead make `autoPlacement()` use a "no space" strategy for the `crossAxis` while it keeps a "most space" strategy for the `mainAxis`

**Comment by jnhooper** [comment]
Thanks so much for the quick response! Your suggestion was exactly what i needed for my use case!

**Comment by atomiks** [comment]
fwiw I marked this as "Blocks Floating UI v1" because I think `flip()` and `autoPlacement()` should be merged into a single middleware where `mainAxis` and `crossAxis` have a strategy of either `mostSpace` or `noSpace` (or something), I just don't know what the API looks like because their options still are quite different

**Comment by atomiks** [comment]
After experimenting it's too hard to "merge" these I think (plus, it stops treeshaking their different parts). 

While they can't be used together, I amended the docs to clearly state the use case for `autoPlacement` and when to use it over `flip`.
