### ISSUE TITLE
Any working examples?

### ISSUE THREAD

**Issue by G2G2G2G** [floating-ui/floating-ui#1677]
There are no working examples?

**Comment by FezVrasta** [comment]
You mean something like these ones? Or something different? May you be clearer please?

<img width="1302" alt="CleanShot 2022-05-05 at 8 58 38@2x" src="https://user-images.githubusercontent.com/5382443/167005248-5e1b40e9-cfc9-4113-ba17-01800fa02082.png">

**Comment by G2G2G2G** [comment]
I guess I mean a demo?
Where is the code in it's entirety to do each of those?


This has many
https://github.com/SortableJS/Sortable
like:
http://sortablejs.github.io/Sortable#thresholds
https://jsbin.com/zosiwah/edit?js,output
https://jsbin.com/numakuh/edit?html,js,output
etc, about 50 others

**Comment by atomiks** [comment]
It's a little hard to demo this library because it depends on specific positions for everything beyond the basic placement/anchored position. i.e., when does the `flip` actually happen, same for `shift`, `size`, etc. Each middleware doc page has its own demo which shows when it's useful.

The ones on the homepage showcase very specific scenarios but you generally want to use a combination of them and it's hard to know which ones are truly needed for your case in a way that prevents the consumer from over-importing modules to solve their use case.

The scrolling containers can be also confusing because:

- The person may not be using a scrolling div container on their page and don't see that it's also related to the viewport/window scrolling container, which performs the same work.
-  They may not understand why it needs to constantly readjust while scrolling but that's just a demo of how `computePosition()` works when repeatedly called, and that each call represents a discrete position

**Comment by atomiks** [comment]
the homepage demos have CodeSandbox links now fwiw
