### ISSUE TITLE
Tooltip is displayed on top of target when there is a parent with `float: right;` and position `right`

### ISSUE THREAD

**Issue by gspasov** [floating-ui/floating-ui#1736]
When the target is wrapped in a parent that has `float: right;` _(or even if the target itself has `float: right`)_ and the tooltip placement is set to `right` _(expecting it to be positioned to the left since there is no space on the right)_, the tooltip actually shows up on top of the target. 

On top of that _(no pun intended)_, the tooltip is getting larger and larger the more you hover over the target. Basically it's size is growing depending on how many times you hover over it, to the point where it will go fully to the left (where it's supposed to be), but will go off screen on the left size (if the text in the tooltip is long enough). It's just growing up until the point the whole text is on one line.

Repro: https://codesandbox.io/s/floating-ui-dom-template-forked-c2lekv

**Comment by gspasov** [comment]
Yeah, setting `top` and `left` to 0 at the beginning seems to remove the problem. Thank you for the quick reply.

**Comment by atomiks** [comment]
I think this is worth adding to the docs. Note that your example still doesn't work with `top/left: 0` because it's too big to fit in the viewport.

In this case `size` comes in handy. This also allows you to use `left/right` placements on small screens instead of flipping to top/bottom: https://codesandbox.io/s/floating-ui-dom-template-forked-1kjbub?file=/src/index.js

**Comment by gspasov** [comment]
Oh sure, I fixed the sizing issue by applying `maxWidth` but your solution seems more general. So I'll look into using that. Thanks!
