### ISSUE TITLE
Placement fallback "bottom" doesn't work if fallback list contains "right" and tooltip is larger than target

### ISSUE THREAD

**Issue by gspasov** [floating-ui/floating-ui#1738]
## Describe the issue

When you setup `fallbackPlacements` with `["bottom", "right"]` the library doesn't put the tooltip to the `bottom` even if there is actual place for it.  

### Additional info
This appears to happen when only when tooltip is larger than the target.

I'm pretty sure this would happen with "left" as well, if there is actual place for the tooltip to go left. IMO the library wrongly decides that there is no place to put the tooltip to the bottom, although there might be some considerations for this that I'm not taking into account.

### Repro
 https://codesandbox.io/s/floating-ui-dom-template-forked-rrrx56

**Comment by atomiks** [comment]
It's working as expected - the problem is `shift()` is placed after `flip()`, and so `flip()` performs its checks with no shifting done. This means it doesn't fit on the crossAxis when placed on the bottom, because shift has not done anything yet, therefore it chooses `right`

**Comment by gspasov** [comment]
If I place `flip()` after `shift` now with the following options, for some reason it's considered that `top` is "bestFit", even though you can't see any of it. This behavior is not happening if I have first `shift` and then `flip`.

Mind you with such long text it's bad anyways, but still, I would wonder why is it considering `top` to be the "bestFit".
Is there a good way to make it fit on the right for example if you really want either top or right.

https://codesandbox.io/s/floating-ui-dom-template-forked-rrrx56 _I just edited my sandbox_

**Comment by atomiks** [comment]
Prior to being positioned, the element's width dimension spans the entire width of the viewport (`100vw`). `computePosition()` uses this initial dimension to perform its calculations. When placed on top it fits better than right using its initial width, because it's unaware of what happens **after** the styles get applied (when placed on the right, it resizes itself to fit, but it doesn't know that beforehand. This resizing behavior happens for "right", but not "left" for instance)
