### ISSUE TITLE
[React DOM Interactions] Menu like component closes parent Dialog like component

### ISSUE THREAD

**Issue by rihardsgravis** [floating-ui/floating-ui#1828]
Since React DOM Interactions package version `0.8.0` "Menu like" component's menu item click interaction closes also the parent Dialog component – I cannot find any breaking changes related to this, so not sure if this is a bug or expected behaviour and what should be done to prevent this.  Version `0.7.0` does have the expected behaviour and the Dialog stays open.

Reproduction link consists of combining unchanged "Dialog" and  "Dropdown Menu" components from [Examples](https://floating-ui.com/docs/react-dom-interactions#examples): 
https://codesandbox.io/s/modest-antonelli-k6ln3v

**Comment by atomiks** [comment]
Looks like it's a problem with `outsidePointerDown` in `useDismiss`.

 This PR possibly https://github.com/floating-ui/floating-ui/pull/1797?

Seems like the nearest `FloatingTree` was being detected by the dialog hook, but now it's not. If you remove the `FloatingPortal` in `DropdownMenu` component, it starts working again.

**Comment by atomiks** [comment]
So before it was working due to the `isFocusInsideFloating()` check with the `bubbles: false` option. But this check was faulty, which is why the implementation changed.

For things like this to work, you need to be able to nest floating trees (to continue portalling the menu):

```js
<FloatingTree>
  <Dialog>
    <FloatingTree>
      <Menu />
    </FloatingTree>
  </Dialog>
</FloatingTree>
```

Then the dialog dismiss hook will know that the menu is part of its tree and the outside click detection will work.

This already partially works, but it makes `useFloatingParentNodeId()` break for checking if a particular node is a root. It should be scoped to its nearest `<FloatingTree>`. Once that is fixed then you can nest different floating trees.

---

Couple workarounds for now as mentioned:

- Remove the `FloatingPortal` wrapper from the `DropdownMenu` component - the menu will be inside the Dialog and so the outside click check works as normal
- Disable `outsidePointerDown` in the Dialog's `useDismiss` hook and implement your own custom outside click check to handle this scenario

**Comment by rihardsgravis** [comment]
@atomiks thank you for the response. Unfortunately I cannot really remove the portal form `DropdownMenu` due to specifics of our implementation, but disabling `outsidePointerDown` works as a workaround 👍
