### ISSUE TITLE
[React DOM Interactions] Examples provided break when `<button />` is swapped for a component `<Button />`

### ISSUE THREAD

**Issue by evangeline** [floating-ui/floating-ui#1832]
Hello! I've been testing out React DOM interactions and noticed that I couldn't get any of the examples to work once I substitute the reference element for a react functional component. I've modified the provided sandbox to demonstrate what I mean: clicking or hovering over the reference element no longer triggers a floating element.

[Popover](https://codesandbox.io/s/serene-bose-kfjcsl?file=/src/App.tsx) | [Tooltip](https://codesandbox.io/s/determined-wood-k5lcjc?file=/src/App.tsx)

This is such a trivial example that I'm surprised it does not work, I might be missing something here.

**Comment by atomiks** [comment]
Take la ook here: https://reactjs.org/docs/forwarding-refs.html

**Comment by evangeline** [comment]
@atomiks Thanks for the quick response. I've managed to get it working.

I have a few questions about DX though:
1. Is forwarding ref and props to the child the recommended pattern? Any child component could be passed in, and this forces the dev who is using `Popover` or `Tooltip` to modify their component, instead of a "plug and play" interface where it just works. 
2. Is it reasonable to build a wrapper that takes the forwarded ref and props instead, for example like so:
```
const ReferenceWrapper = forwardRef<any, any>(({ children, ...props }, ref) => {
  return (
    <span {...props} ref={ref}>
      {children}
    </span>
  );
});

// Tooltip.tsx
<>
  <ReferenceWrapper {...getReferenceProps({ ref })}>
    {children}
  </ReferenceWrapper>
  {open && (
      <div
        {...getFloatingProps({ 
  .....
```
https://codesandbox.io/s/determined-wood-k5lcjc?file=/src/ReferenceWrapper.tsx

This preserves the child component as is and makes using the floating component a lot more frictionless. I can see downsides of not attaching the ref directly on the child however, curious what your thoughts are.

**Comment by atomiks** [comment]
All reusable components you build should `forwardRef`. For example, `styled-components` and `emotion` do it so you can attach refs to their components. React should allow passing `ref` in the future as a normal prop, and it's annoying in the meantime that we still need to use this wrapper function which worsens DX.

Using a wrapper tag is bad because the props will not be attached to the correct element, like `aria-describedby` (the span doesn't receive focus but has the attr attached to it, so screen readers will not announce the tooltip content). The tooltip also only coincidentally shows when the button gets focused because of the consumer ref preservation in the example.
