### ISSUE TITLE
[React DOM Interactions] `useHover` stops working when reference is conditionally rendered

### ISSUE THREAD

**Issue by MariemMhenni** [floating-ui/floating-ui#1833]
@floating-ui/react-dom-interactions version 0.9.1

When My Component is mounted useHover works
if I hide the element and when he reappears useHover doesn't work

https://codesandbox.io/s/o2hozl

step 1 : hover on element menu => work
step 2 : click on hide MENU
step 3 : click again on hide menu
step 4 : hover on element menu => no working

I try to use update() from useFloating but it doesn't work.

Also it doesn't work when I use navigation.

**Comment by atomiks** [comment]
Due to conditional rendering on the reference not being checked as events are registered inside an effect:

https://github.com/floating-ui/floating-ui/blob/28eb62929a325c878e7d128e2bedb5631d185c06/packages/react-dom-interactions/src/hooks/useHover.ts#L155-L158

For now, a workaround is to use `display: none` without conditionally rendering the reference element, but I think storing the reference element inside state instead of a plain ref will be required to ensure the effect runs again correctly.

**Comment by MariemMhenni** [comment]
> Due to conditional rendering on the reference not being checked as events are registered inside an effect:
> 
> https://github.com/floating-ui/floating-ui/blob/28eb62929a325c878e7d128e2bedb5631d185c06/packages/react-dom-interactions/src/hooks/useHover.ts#L155-L158
> 
> For now, a workaround is to use `display: none` without conditionally rendering the reference element, but I think storing the reference element inside state instead of a plain ref will be required to ensure the effect runs again correctly.

thanks
with "display: none" it works
