### ISSUE TITLE
Disabled children disable floating-ui

### ISSUE THREAD

**Issue by gyto23** [floating-ui/floating-ui#1841]
Hi,
I am using `@floating-ui/react-dom-interactions` and when I am disable children of the component I am not getting any of the tooltip to show up:

```js
<Tooltip label="test">
   <button disabled={true}>button</button>
</Tooltip>
```

I know this is silly question but how it possible to avoid Tooltip to be disabled on it own without adding any `divs` on top of the button, but just using generic code

I am using one of the examples were provided https://codesandbox.io/s/winter-tree-wmmffl?file=/src/Tooltip.tsx

**Comment by atomiks** [comment]
You shouldn't attach tooltips to `disabled` elements. Instead, make it visually disabled with `aria-disabled="true"` and just early-return any events in handlers that fire from it.

**Comment by ericbaal** [comment]
> You shouldn't attach tooltips to `disabled` elements. Instead, make it visually disabled with `aria-disabled="true"` and just early-return any events in handlers that fire from it.

Having the same issue.  Why wouldn't you want to be able to have a disabled button and give a tooltip on why it is disabled ("you don't have access to this feature" or "you need to do x y z...")?

**Comment by EvHaus** [comment]
One problem with using `aria-disabled` is that `testing-library`'s `toBeDisabled()` won't play nicely with it. See https://github.com/testing-library/jest-dom/issues/144 for more info.

If that's important to you -- you'll need to keep using `disabled={true}` but wrap your `button` with an extra `<div>` around it.

**Comment by pushkatel** [comment]
@EvHaus  Posted at the same time as I found this thread. I'm sure I will need to test my button. 

Are there any downsides to using `<div>`, other than it just looking a bit wonky?

**Comment by EvHaus** [comment]
> Are there any downsides to using <div>, other than it just looking a bit wonky?

Yeah, you'll need to deal with styling accordingly. And in general, extra DOM nodes introduce a bit of performance overhead but in most cases you won't notice it.

**Comment by atomiks** [comment]
The wrapper workaround isn't accessible, see:

- https://floating-ui.com/docs/react#disabled-elements
- https://floating-ui.com/docs/tooltip#disabled-buttons

I'm not sure why a test matcher would be more important than something being accessible to users. What's wrong with `.toHaveAttribute('aria-disabled', 'true')`?

**Comment by EvHaus** [comment]
> What's wrong with `.toHaveAttribute('aria-disabled', 'true')`?

It's not terrible, just slightly less convenient. 

My only real problem is that the `floating-ui` docs say to disable the `onClick` event handlers and "all relevant event handlers":

```js
// You'll want to do this for all relevant event handlers.
onClick={visuallyDisabled ? undefined : props.onClick}
```

In some cases, it's not easy to figure out which event handlers are relevant. For example, for a11y you'd probably also want to disable any `onKey*` handlers to prevent keyboard based button activation. And maybe some of the `onMouse*` handlers -- although, not all, because that would break the tooltips again.

Since you have to control the behaviour of the disabled state in code now, rather than letting the browser do the heavy lifting for you -- it would be helpful to know exactly which events should be kept enabled for `floating-ui`.
