### ISSUE TITLE
[DOM] `hide` middleware `referenceHidden` incorrect when reference ancestor is `position: absolute` 

### ISSUE THREAD

**Issue by boomler** [floating-ui/floating-ui#1867]
For the following HTML structure, hide middleware return `true`, indicate that reference element been hided.
Event though its parent is  `overflow:hidden` and computed style `height: 0`,  actually  `position: absolute` make it related with outer relatived ancestor.

```
    <div style="position: relative;">
      <div style="overflow: hidden; border: 4px solid green;">
        <div style="position: absolute;">
          <div id="reference"></div>
        </div>
        <div id="floating">Floating element</div>
      </div>
    </div>
```

sandbox: https://codesandbox.io/s/mutable-browser-euniq7?file=/src/index.js:318-369

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/17810913/186085726-626b39f7-5316-4317-9efe-13c76409a214.png">

**Comment by atomiks** [comment]
In the Sandbox I see it's been edited so that the reference element has `position: absolute` instead of the ancestor which fixes the issue.

Probably need to check every ancestor between the reference element and its clipping ancestor and see if any of them `absolute`?

**Comment by boomler** [comment]
@atomiks After I upgrade to 1.0.4, when with multiple `position: absolute` ancestor, it still works not right. see: https://codesandbox.io/s/condescending-bell-v4sx4n?file=/index.html

**Comment by atomiks** [comment]
Rip, did feel like there would be more complex cases to handle than the few tests I wrote. 😞

**Comment by atomiks** [comment]
@boomler if you can, can you try out the fix from https://github.com/floating-ui/floating-ui/pull/1956? I kind of changed the whole algorithm which simplified things. The tests pass, but maybe some edge case is still lurking 😢

**Comment by boomler** [comment]
@atomiks Nice work!  👍🏻  Would you mind publish a new version ?

**Comment by atomiks** [comment]
@boomler it fixes all the cases you had?

**Comment by nicolechung** [comment]
Is popper (version 2.x) not being supported for this fix?

**Comment by atomiks** [comment]
Since I don't have the energy to maintain the two libraries simultaneously, the current policy is that Popper is still receiving new versions but only from fixes via external contributors. So if you make a PR on `v2.x`, add tests and everything passes etc., then we can release a new version. You'd have to port the logic over though.

**Comment by gavinxgu** [comment]
@atomiks I tried #1923, but found some bugs in `getClippingElementAncestors`. So I made a new PR https://github.com/floating-ui/floating-ui/pull/1959 to fix it. Could you please do a CR and figure out whether there are new bugs or anything that has not been considered? 

The main purpose of `getClippingElementAncestors` is to **drop non-containing block**. My thoughts are as follows.
1. do recursion in the parent elements chain.
2. when we encounter a node
   1. if the current containing block is null, record it and continue.
   2. if the current containing block's position is `absolute` or `fixed`, drop `currentNode` which is a non-containing block.

We don't need to drop the non-containing block when the current containing block's position is `static`, `relative`, or `sticky`,  because blocks with these positions will always be **contained**
