### ISSUE TITLE
[React DOM Interactions / FloatingOverlay] Is it possible to use together with the react-toastify?

### ISSUE THREAD

**Issue by S-Ladros** [floating-ui/floating-ui#1883]
I'm using modal window from your example together with the react-toastify module.

When modal window is open and toast are shown, I'm trying to close the toast, but together with the toast modal window closes too.

Is it possible to prevent a closing of the modal window whem I'm clicking an another element around the borders of the modal window content?

Thank you.

**Comment by atomiks** [comment]
If it's rendered inside the Dialog's React tree it won't close. Otherwise you could disable the `useDismiss` hook (`enabled` option) while pressing on the toast element.

**Comment by S-Ladros** [comment]
> If it's rendered inside the Dialog's React tree it won't close. Otherwise you could disable the `useDismiss` hook (`enabled` option) while pressing on the toast element.

Thank you for the answer, but, how can I sync toaster onClick with the useDismiss which located in Dialog.tsx?

**Comment by atomiks** [comment]
You would need to use some kind of global state most likely.

As long as the toast is either:

- Rendered inside the floating element's DOM tree, or;
- Rendered inside of its React tree (which can be portaled like so):

```js
<div ref={floating}>
  <span>My dialog</span>
  <Portal>
    <div id="toast-element">My toast</div>
  </Portal>
</div>
```

The toast element will not close when clicking on it due to the `outsidePress` logic in `useDismiss`. Otherwise you'll need to disable `outsidePress` while the toast is mounted on the screen.
