### ISSUE TITLE
[QUESTION/FEATURE REQUEST] Include margins in flip and other middleware (offsetHeight/offsetWidth)

### ISSUE THREAD

**Issue by fredboyle** [floating-ui/floating-ui#1887]
We are building a design system based toolkit and as such all our size, spacing, and such foundational values come from design tokens and are either unit-less or in relative units (rem/em).

This means that when using Floating UI we cannot use the `offset()` middleware as it only accepts pixel values and also cannot reference a CSS design token. We can use CSS directly to properly add spacing/offset in the default initial position of our floating element but once middleware such as `flip()` take action things get misplaced since the margin values are not taken into account during the calculations for the new position.

It would be great if `flip()`, and other middleware, had an option to either apply a positional CSS class (user specified array or automatic such as `fui-block-start | fui-inline-end | ...`) or data attribute (`data-fui-position='block-start | inline-end | ...') or even an option flag to include `getComputedStyle().margin<logical position>` values in the positioning calculation.

Would be great to hear what the maintainers think about this kind of enhancement.

**Comment by fredboyle** [comment]
Put together a quick hack for a component but it would still be nice if Floating UI did this automatically.

```js
// Add the Floating UI data attribute
if (refs.elem.current) {
	refs.elem.current.dataset.fuiPlacement = placement;
}
```

The CSS below simply converts the default top margin to be negative to shift things appropriately when `flip()` takes action and moves things from the bottom to the top.
```css
[role='menu'][data-fui-placement^='top'] {
	margin-block-start: calc(token('spacing.2XS' to rem) * -1);
}
```

**Comment by atomiks** [comment]
Margins aren't supported as they interfere with the lifecycle and can't be computed ahead of time. Only the exported `offset()` middleware is supported, as it doesn't need to write to the DOM in the middle of the lifecycle. The data attribute you have is one workaround but it's not something that will be built in because of that (cross-platform & perf concerns, extra burden of adding config, etc).

You can convert `rem` into `px` to be consumed by `offset()` using px-to-rem packages available on npm.
