### ISSUE TITLE
[Core] `size` middleware gives wrong `availableWidth`

### ISSUE THREAD

**Issue by 1593292349** [floating-ui/floating-ui#1897]
availableHeight is right, but availableWidth is wrong
https://codesandbox.io/s/floating-ui-dom-template-forked-k2y1nu?file=/src/index.js

**Comment by atomiks** [comment]
It's not wrong, the `availableWidth` takes into account what type of alignment the placement has. 

If the width exceeds the number displayed, it will no longer have a center alignment (for the default `bottom` placement), and will also overflow when `shift()` is not used.

**Comment by 1593292349** [comment]
@atomiks I don't want to worry about alignment, how do I get the maximum width?

**Comment by atomiks** [comment]
You can set `width: 100vw;` in the CSS of the floating element, and use `shift()` to prevent it from overflowing anywhere on the page

**Comment by 1593292349** [comment]
@atomiks No, because it's probably in a very small scroll container

**Comment by atomiks** [comment]
You can set the width to be the same as the scrolling container in JS (assuming it clips it), then use `shift()` also. Or keep it portalled outside of it so it can always span the width of the page. Or create a custom middleware that leverages [`detectOverflow`](https://floating-ui.com/docs/detectoverflow) to do what you want dynamically regardless of the context it will live in.

**Comment by 1593292349** [comment]
@atomiks Thank you, I hope Size Middleware will do this and provide an option indicating whether to consider it or not what type of alignment the placement has.

**Comment by atomiks** [comment]
I'm thinking if we detect if `shift()` is in use before `size()`, then it should consider the entire width as available. (Sorry for late reply/decision)

**Comment by Westbrook** [comment]
That would be an interesting addition to the API. I'm seeing a similar result (the `availableHeight` is representing the full viewport minus padding from the `shift()` plugin and then again from the `size()` plugin) in another context and I wonder if this approach would help me. Are there other contexts where the plugins already applied are tracked so I might test what this looks like?

**Comment by Westbrook** [comment]
Oh, that PR is not directly related to an issue in Floating UI. What I found while fixing an unrelated issue is that `shift()` and `size()` used together can give me a measurement that is an extra `padding` smaller than it should be when attempting to acquire the max measurement a floating element can have.

**Comment by atomiks** [comment]
After working on this a bit, it's kind of ambiguous how certain things should behave and can be confusing.

To summarize how `size()` currently works for center placements where the available dimension runs along the crossAxis:

- It detects the available dimension length that ensures the placement will remain centered — not the whole width/height of the viewport, because then it will overflow _unless_ `shift()` is used before it. This can be done internally but as I said there are some ambiguities in some cases.

As a result, I think the best option is a custom middleware that uses `detectOverflow`. If you have `shift()` before the custom middleware, it will work as expected.

The custom middleware basically will just do this:

```js
const overflow = await detectOverflow(middlewareArgs);
const availableHeight = -overflow.top - overflow.bottom + rects.floating.height;
const availableWidth = -overflow.left - overflow.right + rects.floating.width;

// Mutate size with these values.
```

**Comment by Westbrook** [comment]
This _roughly_ works, but using it instead of `size()` looses a lot of capabilities that I'd like to take advantage of without having to rebuild myself. Other than having `padding` subtracted multiple times when gathering the available rect, I don't currently have any issue with `size()` even if I find the summary above a bit confusing in relation to the naming/docs currently available. 

I wonder if it's actually the non-stateful calls to `detectOverflow` that cause this situation? Each call to `detectOverflow` that is provided with `padding` will have that value remove from the available rect: https://github.com/floating-ui/floating-ui/blob/master/packages/core/src/detectOverflow.ts#L107-L124 What's more, the available rect is made without concern for the `placement`, so while the `padding` should be offset from the clipping edge, even if the `placement` is `bottom*` meaning the available rect doesn't approach the clipping edge, as it approaches the reference element instead, the `padding` will still be adjusted for both sides of the available rect. Do this once for `flip()` and then later for `size()` and assuming the available rect hasn't moved you begin to have a smaller and smaller rect for each call. It _feels_ like `detectOverflow` should only be called once (for every time the placement changes) and then the returned values should ride along with the `middlewareArguments` for easy use in subsequent middlewares...

**Comment by atomiks** [comment]
I'm not sure I really understand the problem, do you have a CodeSandbox/demo?

**Comment by Westbrook** [comment]
Well, I can't even really get to the issue at hand because `size()` doesn't seem to work in the way that I expect in this demo: https://codesandbox.io/s/peaceful-forest-n6iqc7?file=/src/index.js:564-819 

Here, I'd expect the `maxHeight` returned by `size()` to be `100vh - ${padding * 2}` (which is not what I get in my local application), but I can't even get that in this simplified context...

**Comment by atomiks** [comment]
Yeah I guess this should work better 😕 `right-start` works as expected. Maybe instead if `shift()` is detected before `size()`, it should use the aligned placement math instead.
