### ISSUE TITLE
safePolygon broken?

### ISSUE THREAD

**Issue by maccman** [floating-ui/floating-ui#1901]
It seems the version bump from react-dom-interactions 0.8.0 to 0.8.1 broke safePolygon.

Here is an example with safePolygon working.

https://codesandbox.io/s/safe-polygon-working-qk5w69

Here is an example with it not working.

https://codesandbox.io/s/safe-polygon-not-working-0vk921

The only change seems to be this one.

https://github.com/floating-ui/floating-ui/pull/1808/files

**Comment by atomiks** [comment]
I'm not sure I understand, both versions are working for me in the sandboxes

**Comment by atomiks** [comment]
Okay, I see what you mean. You mean `pointer-events` is now being removed incorrectly in some situations which causes the hover events of the nearby reference elements to fire, so you can't reach it; seems like it only happens when you're using a delay group. 

And yeah, https://github.com/floating-ui/floating-ui/pull/1814 is the best solution, but doesn't work in Firefox currently.

**Comment by atomiks** [comment]
Since the fix was intentional to ensure a different issue was fixed with delays, I think that you should just remove the delay group in this component. It doesn't actually do anything useful and does not need to be added. The logic will work as expected once you remove it.

**Comment by maccman** [comment]
Thank you - appreciate you getting back to me.
