### ISSUE TITLE
[Question] How to flip Nested Component

### ISSUE THREAD

**Issue by jun2077681** [floating-ui/floating-ui#1950]
For the desired placement, the popover should be below the target component and the tooltip should be below the popover.
If the target is almost on the floor, flip the placement from target - popover - tooltip order to tooltip - popover - target.

The popover is bound to the target by useFloating, and the tooltip is bound to the popover.
Contrary to the desired result, the popover is flipped against the target, but the tooltip is not flipped because there is space under the popover after being flipped by the target.

How do we design it to make it work as intended?

![image](https://user-images.githubusercontent.com/20516642/200773216-92023777-71d4-436d-a07f-4c37a34e7bbd.png)

**Comment by atomiks** [comment]
It seems related to this issue: https://github.com/floating-ui/floating-ui/issues/1440

I think as a workaround, you could store the popover's placement state and change the tooltip's placement based on that. e.g.

```js
const {placement} = useFloating(); // popover
const data = useFloating({placement}); // tooltip
```

Of course, if the tooltip does need to genuinely flip due to lack of space, then it will overlap still.
