### ISSUE TITLE
[React Dom Interactions] Problem with async data source and usenavigation 

### ISSUE THREAD

**Issue by clarknova** [floating-ui/floating-ui#1958]
Hello when the data used to render a autocomplete combobox arrives async it breaks the list navigation:

I forked the combobox example and modified it to illustrate the issue: 
https://codesandbox.io/s/inspiring-moser-ezzx74?file=/src/App.tsx
Reload the Sandbox. Type in the Letter O. After 10 sec the Data arrives and populates the list. When I try to navigate I have to press the up or down button twice to start navigating.

I think the problems has todo with the refs because when I do 
```  const listRef = useRef<Array<HTMLElement | null>>([null]);```
instead of 
```const listRef = useRef<Array<HTMLElement | null>>(null);```
it works normal

I do the filtering of the data server side so this is a real scenario.

**Comment by atomiks** [comment]
If you disable the hook while the data is loading it also works fine:

`enabled: data.length > 0`

Could look into making it more resilient in async cases when the whole list is empty.

**Comment by atomiks** [comment]
So after looking at this more, I don't think there is anything that needs fixing. The problem is that the example sets the `activeIndex` to `0` despite there being no data. You can guard this:

<img width="608" alt="Screenshot 2022-11-15 at 11 06 26 pm" src="https://user-images.githubusercontent.com/22450188/201915897-e1a04096-0ebb-4808-9bd3-96279a043e15.png">

If you want it to automatically focus once the data loads in even if nothing else is typed etc., you can then use a setter to set the index to `0`.

```js
if (open && data.length && activeIndex === null) {
  setActiveIndex(0);
}
```

Note: you don't need an effect, see: https://beta.reactjs.org/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes

This should be documented though, way better docs are coming for everything soon

**Comment by piecyk** [comment]
@atomiks maybe you saw this behaviour, basic when calling `setActiveIndex` in render, running react 18 in stick mode the second render is using old state value, something like this 

```
activeIndex: 0
activeIndex: 0
setActiveIndex(2)
activeIndex: 2
activeIndex: 0
```

My use case here is pretty simple, to setActiveIndex for option that exact match input value.
