### ISSUE TITLE
Prevent dismissing when clicking in certain element outside

### ISSUE THREAD

**Issue by hornta** [floating-ui/floating-ui#1982]
When clicking a floating element I don't want the click to dismiss the current floating element even though I want it for other clicks. The example shows the problem I'm having where I trigger a notification(that isn't rendered inside of the current floating element) and clicking on the close button. 

I would think I could have a click listener on the `useDismiss` options that I could prevent it from being registred as an outside click if I click on something that has a certain data attribute or something.

*Clicking on the close button of the alert closes both the alert AND the modal. I don't want the modal to be closed in this instance.*
![Animation (2)](https://user-images.githubusercontent.com/4553604/204631910-496d6265-acef-4aac-8e7f-93a63a210028.gif)

**Comment by atomiks** [comment]
The issue was filed here but there wasn't any great resolution: https://github.com/floating-ui/floating-ui/issues/1883

The ideal solution is to ensure the toast is rendered inside the floating element's React tree (doesn't need to be its DOM tree). But since this isn't possible with some external libraries we should come up with some escape hatch I guess.

> prevent it from being registred as an outside click if I click on something that has a certain data attribute or something.

I think some callback like `validateOutsidePress: (event) => boolean` could work. You could check if the `event.target` is inside the external toast element and return either true or false, where false would cancel the dismissal.

**Comment by hornta** [comment]
Although I'm not using an external library it's still effectively the same issue, yes. When I built the notifications I couldn't come up with a nice way of rendering them inside the floating element AND having them stack together nicely in the corner in a queue like fashion, so such a callback would be really nice to have.

**Comment by atomiks** [comment]
You can use a portal inside the floating element's React tree, to move them outside its DOM tree. Then the floating element's layout won't affect the toasts but the outside press logic won't break.

**Comment by hornta** [comment]
I guess this would mean I have to render a notification explicitly in JSX from inside the modal where I want the toast. Right now I've built it so I can from anywhere, even outside react components, call a `showNotification` function. It's heavily inspired by https://mantine.dev/others/notifications/#functions I like that I don't have to think about any states or such from where I want to trigger a toast but to the cost of it being wired globally.

**Comment by atomiks** [comment]
I wonder how Mantine or other libs handle this case, do they do anything special? When one of those toasts is rendered on their dialog

**Comment by hornta** [comment]
In their case I believe the modal checks explicitly for clicks on the overlay element so it's basically ignores clicks on anything, so that's that, but they do also have a hook for managing what happens when clicking outside an element with a somewhat hard coded escape hatch by checking if the clicked element has a certain attribute or not. 

https://github.com/mantinedev/mantine/blob/7e40ca99ad2572dcc416bf2a4417cf38d89e47de/src/mantine-hooks/src/use-click-outside/use-click-outside.ts#L17

**Comment by atomiks** [comment]
Okay so I see two options (can do both):

- Extend `FloatingOverlay` to accept outside presses like `useDismiss` does — you'll then set `outsidePress: false` for `useDismiss`.
- Make `useDismiss`' `outsidePress` accept a function, which when specified acts like `true` but also a guard to do checks like: `outsidePress: event => !event.target.closest('[data-ignore-outside-press]')` (this allows further control rather than a hardcoded attribute).

**Comment by atomiks** [comment]
So if I'm understanding correctly, your tree would need to look like this (always wrapped in `FloatingTree`):

```js
<FloatingTree>
  <Modal />
  <Notifications />
</FloatingTree>
```

And you want to signal to `<Toasts />` that it `<Modal />` should be its parent even though it's a sibling in the React tree? When you attach a modal to a random button, how do you know to render it inside the FloatingTree, or the provider is just high up in your app such that it always wraps both, even if the `<Modal />` is nested deeply?

**Comment by hornta** [comment]
In my case I placed `<FloatingTree>` in the top of the app along with all other "global" components like our AuthProvider, ReduxProvider, I18N provider and such so there will always be a FloatingTree available. The `<Notifications />` is also rendered at that level, however under the floating tree of course. 

I guess the more normal thing would be to render a floating tree inside of the modal

**Comment by atomiks** [comment]
It needs to wrap the Notifications component so I think what you're doing makes sense. Anyways I think I'll make a PR that adds the function guard option to `outsidePress` and also the ability to specify a custom parent in FloatingTrees
