### ISSUE TITLE
Updating reference don't work anymore

### ISSUE THREAD

**Issue by Mario-Eis** [floating-ui/floating-ui#2091]
As described in the Docs under [@floating-ui/react](https://floating-ui.com/docs/react#refs) it should be possible to update the reference with 

```
 useLayoutEffect(() => {
    reference(referenceElement);
  }, [reference, referenceElement]);
```

0.14.0 was the last version where this was working. 0.15.0 and above just set the refence once and never update it again. I am using virtual elements (https://floating-ui.com/docs/virtual-elements#usage) to set the position of the floating popup to the mouse cursors click position. With >0.15.0 the Popup is stuck on its first position.

**Comment by atomiks** [comment]
Do you have a CodeSandbox reproduction? Are you using state to store the external element, or a plain ref?

**Comment by atomiks** [comment]
Okay, I see you're using virtual elements, the new [`positionReference`](https://floating-ui.com/docs/react#changing-the-positioning-reference-while-retaining-events) callback ref will allow for that instead.

It was meant to be backwards-compatible but it seems the old technique no longer handles updating properly.

**Comment by Mario-Eis** [comment]
So instead of the reference, we should use positionReference now?

**Comment by atomiks** [comment]
Going forward yes, as it was possible for the old technique to be overwritten if the reference element's `ref` callback was unstable between renders, e.g. in other component libs which you don't control. So it's more reliable. However, the old way should continue to work which the PR should fix.

**Comment by akinnee** [comment]
Thanks for explaining how to fix it. In the meantime I've had to override this dependency in another dependency because this is a breaking change, but minor version bumps should not include breaking changes so npm is installing 1.1.x and my dependency is expecting things to still work the way they did in 1.0.x.
```
"overrides": {
    "some-other-dependency": {
      "@floating-ui/core": "1.0.1",
      "@floating-ui/dom": "1.0.1",
      "@floating-ui/react-dom": "1.0.0"
    }
  },
```

**Comment by atomiks** [comment]
You don't have `@floating-ui/react` installed, where it's in `v0` and minor changes are considered potentially breaking. 

So your issue must be different, what problem are you facing?

**Comment by atomiks** [comment]
@akinnee I've merged the PR which closed this issue because it affects `@floating-ui/react` _not_ `@floating-ui/react-dom` which you seem to be using, but you can open a new issue with a reproduction using the dependency causing the issue.

To give more context, there were two changes made from `v1.0.1` to `1.1.0` and `v1.1.1`:

- In `v1.1.0`, the layout effect that caused an update when `placement`, `middleware`, or `strategy` changed was removed as it was redundant. The callback ref now changes during render, which causes React to call it with `null` and then with the new `node` again, which causes an update anyway. This shouldn't cause a bug unless there's an edge case not being considered.
- In `v1.1.1`, the callback refs now check if the current node stored in the ref is different from the one being invoked with the callback ref, and only then perform a new update. Again, this shouldn't cause an issue in theory because React always calls it with `null` before the next node, and if it's a different node, the `!==` check handles it also.

So if you try out `overrides` with `v1.1.0` vs. `v1.1.1` of `@floating-ui/react-dom`, it can help identify if it was the layout effect being removed, vs. the guard check causing the issue. And even then, it seems like the dependency itself likely isn't using `autoUpdate` and was relying on flaky re-renders to cause updates, which also affected https://github.com/floating-ui/floating-ui/issues/2086#issuecomment-1369891879.

**Comment by akinnee** [comment]
@atomiks Thanks for the additional info. Followup issue here, but it sounds like you can mark it resolved. https://github.com/floating-ui/floating-ui/issues/2096
