### ISSUE TITLE
Link/button got focused automatically inside Dropdown Menu

### ISSUE THREAD

**Issue by sparanoid** [floating-ui/floating-ui#2126]
Forked from the [Dropdown Menu (including submenus)](https://codesandbox.io/s/admiring-lamport-5wt3yg?file=/src/DropdownMenu.tsx) demo. When click the root menu. The first menu item with link/button got focused automatically.

This is not a big issue but this behavior looks weird:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/96356/212761939-a5c82861-2c37-4bae-9d6b-9a02dd0bee54.png">

Demo: https://codesandbox.io/s/blissful-jepsen-tol4q7

**Comment by atomiks** [comment]
You need to give the `<a>` a `tabIndex={-1}` to ensure it doesn't receive the `initialFocus` of the focus manager.

Also if you try to use the typeahead, it will break as it needs to be a string. I recommend amending `MenuItem` with an `as` prop to render an `<a>` tag instead. (`<MenuItem as="a" />`) rather than making label a non-string.

<img width="442" alt="Screenshot 2023-01-17 at 7 43 37 am" src="https://user-images.githubusercontent.com/22450188/212762707-126de027-4881-4b68-8ca4-8e930b6fc52b.png">
