### ISSUE TITLE
Regression: can't use SVG element as an arrow for tooltip

### ISSUE THREAD

**Issue by Mesqalito** [floating-ui/floating-ui#2137]
When using SVG element as an arrow for arrow middleware in `useFloating` its `middlewareData.arrow.x` returns NaN.

Minimum example:
https://codesandbox.io/s/floating-ui-react-dom-template-forked-324lbp?file=/src/App.js

Working @floating-ui/react-dom version:
1.0.1

Faulty @floating-ui/react-dom version:
1.1.0

Cause:
Method `getDimensions` previously had check if element is `HTMLElement`, now calls `getCssDimensions` which does no such check. Then method gets `offsetWidth` which SVGElement doesn't have.

**Comment by atomiks** [comment]
The arrow types don't allow `SVGElement` (must be wrapped within an `HTMLElement`)

**Comment by Mesqalito** [comment]
Is there a reason for that?

**Comment by atomiks** [comment]
I'm surprised it worked, but I think I know why it now works, as far as I can tell only `offsetParent` is checked which SVGs don't have:

https://github.com/floating-ui/floating-ui/blob/d2407ceba88805053d42828e10dafcabe22fc116/packages/core/src/middleware/arrow.ts#L59

However somewhat recently, it falls back to using the floating element as the offset parent (which is almost always the case) — this may just be a legacy thing from Popper that can be fixed in Floating UI. I'd need to check the relevant tests in the v2 branch, because I don't think it's tested for right now anymore.

Another thing to consider is that the element being measured must be a square to prevent problems when the axis of the arrow changes when flipping, in the example CodeSandbox the SVG is not a square, whereas using an HTML element wrapper makes that more obvious. (Although you can make `<svg>` a square I think, despite the `<polygon>` not being one, so that may not be relevant.)

**Comment by atomiks** [comment]
Yeah sorry that wasn't clear: 

I know that the `dom` package change caused it to stop working, what I was trying to say is why the arrow can't be allowed to be an `SVGElement` in the first place (this dates back many years), and it's because `offsetParent` is accessed on it internally, and I think some other reasons that's probably not relevant anymore given the code has changed a lot since.

While the `getOffsetParent` method accepts an `Element`, the method falls back to the window for SVGs, which wouldn't work in the arrow's case as it should be the floating element. Somewhat recently to fix an issue with `react-native`, the arrow code now falls back to the floating element internally, which is why SVG elements would have started working.

And you're right, your sandbox has the SVG as a square, I was thinking of my [SVG sandbox](https://codesandbox.io/s/determined-hill-7x5g57?file=/src/index.js) where it uses an actual triangle polygon.

So essentially, it wasn't ever explicitly supported (and TypeScript would have been erroring), it just coincidentally worked, and there haven't been any requests to actually allow the arrow to directly be an `SVGElement` as the wrapper `HTMLElement` technique always worked. 

Since it did seem to work before, I'll try to add explicit support for SVG arrows shortly; I'll take a look this weekend.
