### ISSUE TITLE
Feature Request: useContextMenu

### ISSUE THREAD

**Issue by nc** [floating-ui/floating-ui#2141]
So you can have floating ui menus that appear when you context click.

**Comment by atomiks** [comment]
The Context Menu demo shows how to build one of these.

The library doesn't offer hooks like `useContextMenu`, `useCombobox`, `useSelect` etc., not because I don't think they're good ideas, but because I wanted to make it feasible to build any type of component even if the library doesn't support it yet.  So things like `useListNavigation`, `useTypeahead`, and `useRole` are the common primitives used by all of these to build them.

That said, there are areas of improvement here — for example, there could be a hook that handles the virtual element positioning more easily, which also includes things like following the cursor on mousemove and not just click for context menus.

**Comment by atomiks** [comment]
I opened an issue to add a hook for point-based virtual element usage: https://github.com/floating-ui/floating-ui/issues/2150
