### ISSUE TITLE
[React] `getItemProps` changes too frequently causing too many re-renders/breaking `memo`

### ISSUE THREAD

**Issue by csantos1113** [floating-ui/floating-ui#2144]
### Issue

My component gets re-rendered on every internal interaction (hover, focus, keyboard-navigation) when using `useInteractions` hook.

### Expected

Considering that all the hooks are using `useCallback` and `useMemo` (i.e. [useListNavigation](https://github.com/floating-ui/floating-ui/blob/1e22b616beed0307aea16c3db683fea5e92cb72c/packages/react/src/hooks/useListNavigation.ts#L174)) I'd have expected to see no re-rendering, or only re-rendering the pieces that are affected.

### Reproduction example

I've used the CodeSanbox from https://floating-ui.com/docs/uselistnavigation#examples as the base:

https://codesandbox.io/s/eloquent-chatterjee-fi4q3t?file=/src/App.tsx:1877-1892

### Versions

- `@floating-ui/react`: `0.18.1`

**Comment by atomiks** [comment]
The reason it re-renders is because the `activeIndex` is changing, which sets `aria-selected` or focus styles, etc.

**Comment by atomiks** [comment]
Closing since this is expected. 

If you're concerned about performance of your list items, you can memo them and pass in a boolean rather than the `activeIndex`. So even if the `activeIndex` is frequently changing, the boolean only changes when relevant and therefore the list item won't re-render needlessly. In this case, you'll need to pass the prop getter as prop because it would return a new object of props every time otherwise if called from the parent component:

```js
const ListItem = React.memo(function ListItem({active, getItemProps}) {
  return <div aria-selected={active} {...getItemProps()} />;
});
```
