### ISSUE TITLE
Middleware types not re-exported from `@floating-ui/core` in dependent libraries

### ISSUE THREAD

**Issue by VividLemon** [floating-ui/floating-ui#2169]
The @floating-ui/vue package does not export the types for the offset middleware. You'd have to manually make them or use TS magic to get the types, it's not very ideal.

**Comment by atomiks** [comment]
I think this is part of a bigger problem of the types in the base libraries, where if `core` and `dom` have the same type, it's not being re-exported and is only available to import from `@floating-ui/core`. 

Only `SizeOptions` appears to be as it's wrapped specifically.

**Comment by FezVrasta** [comment]
I see TS just added support for `export type *` on the latest beta release. It may come in handy

**Comment by atomiks** [comment]
We support TS 4.1 minimum and will have to for years, so new features are kinda useless to libraries :\ basically the same as browser support minimums.

In any case, there are conflict issues that have occurred due to naming collisions, so each type needs to be individually exported to prevent problems in certain cases it seems.
