### ISSUE TITLE
Support `overlay` placement strategy

### ISSUE THREAD

**Issue by ciampo** [floating-ui/floating-ui#2171]
In https://github.com/WordPress/gutenberg/ we have recently implemented a new `overlay` placement, which forces the floating element to render exactly on top of its reference (see https://github.com/WordPress/gutenberg/pull/47004)

It would be great if we could backport this piece of functionality to `floating-ui`.

@atomiks , could you provide some guidance on how we could help with that?

Thank you!

(cc @ellatrix @youknowriad @jsnajdr)

**Comment by atomiks** [comment]
Is that the same as [`center`](https://floating-ui.com/docs/offset#creating-custom-placements) from this first example?

**Comment by jsnajdr** [comment]
> Is that the same as [center](https://floating-ui.com/docs/offset#creating-custom-placements) from this first example?

Yes, it's that `center` plus resizing the floating element to fully cover the reference element.

**Comment by atomiks** [comment]
[This is the relevant file?](https://github.com/WordPress/gutenberg/blob/29fe4a93d7938bcfb093d4b78f1803fd65d426ca/packages/components/src/popover/overlay-middlewares.tsx)

I think what would be suitable is a placement string that explicitly matches the x/y coords of reference as done there, which is useful as a starting point to combine with `offset()`, rather than adding this feature combo explicitly (considering it's already possible with little effort).

This is actually already the case when you pass an invalid placement, e.g. an empty string, but there could be a special and valid string for it instead, considering TS errors currently.

**Comment by ciampo** [comment]
If I understand correctly, you are proposing a new placement that only matches `x` and `y` coordinates (but not the `width` and `height`) of the reference?

**Comment by atomiks** [comment]
Yes, the main issue is how it acts with things like `flip()` and `autoPlacement()` which rely on the `${side}-${alignment}` syntax and would likely introduce some problems.

**Comment by atomiks** [comment]
I've decided against supporting this directly for two reasons:

1. It's really easy to support yourself externally and isn't super common
2. It causes problems with other parts of the API that rely on the standard placement syntax, reducing cohesion of the library. By adding a custom middleware it helps signal that you won't be using those other parts which don't work nicely with the special placement string

**Comment by ciampo** [comment]
Thank you for considering it anyway, and for stating your reasons clearly 🙏
