### ISSUE TITLE
DOM] Popper placement is wrong when its placed inside a web component where multiple shadowDoms are involved and if the ancestor has transform and translate property	

### ISSUE THREAD

**Issue by srivalli-sivaramasankaran** [floating-ui/floating-ui#2183]
We are using popper.js for one of our [datepicker web component](https://crayons.freshworks.com/components/core/datepicker/) and the strategy as 'fixed' and multiple shadow DOMs are involved. When the web component is placed inside a parent that has transform translate property, the popper placement seems to be wrong.

**Code Sandbox**

https://codesandbox.io/p/sandbox/charming-flower-9x0ezp?file=%2Fsrc%2FApp.tsx

**What went wrong ?**
On Clicking the datepicker, the dropdown should appear below the component. However, the dropdown now appears at the end of the page. (Please scroll down to see the date picker dropdown.)

**Screenshots:** 

<img width="600" alt="Screenshot 2023-02-15 at 1 59 54 PM" src="https://user-images.githubusercontent.com/12458149/218973843-b5c47706-faab-4d94-bbad-809678682a0a.png">

**Comment by thiyagarajan17** [comment]
I would love to take a look into it.. could you assign the issue to me

**Comment by thiyagarajan17** [comment]
Could work on the style attribute on the fw-datepicker attribute to make it consistent

**Comment by thiyagarajan17** [comment]
<img width="1058" alt="issue_nego" src="https://user-images.githubusercontent.com/39094923/218981281-2347d528-b623-41fe-ba95-19ebe2f00a0e.PNG">

I have found a fix to PR

**Comment by atomiks** [comment]
We have now released [Floating UI v1](https://floating-ui.com/docs/motivation), the successor to Popper.

Don't worry, Popper 2 will **continue to receive new releases** with bug/security fixes provided by external contributors, but development of new features is not continuing at this point. We are also closing bugs related to it as us maintainers are focusing our energy on tracking issues with Floating UI, however you are welcome to create new pull requests to fix bugs in Popper, which we will review and merge, as many packages (such as MUI, Bootstrap, etc) still rely on it. 

This issue has been fixed in Floating UI, but you are welcome to create a new PR to fix it in Popper as well. The PR with the fix is here, which needs to be ported to Popper: https://github.com/floating-ui/floating-ui/pull/1827

Thanks!
