### ISSUE TITLE
Popper not positioned correctly if reference element is scaled

### ISSUE THREAD

**Issue by endosama** [floating-ui/floating-ui#2184]
Having some issue with popper positioning in case of a scaled element (in my case, an iframe) inside a not scaled page. 

![image](https://user-images.githubusercontent.com/23038474/219041511-42fb49a9-d509-43cd-b8e6-7677a203ec69.png)

Not sure, but may be related to [this scaling ](https://github.com/floating-ui/floating-ui/blob/db4b7ad129b3f79b85184c3c30f352daab824cc3/packages/dom/src/utils/getBoundingClientRect.ts#L61)of the `x` coordinate with the iframe scale, but the x coordinate is not relative to the iframe?

Using `@popperjs/core` `v.2.11.6`
Sandbox: https://codesandbox.io/s/elastic-haze-197srf?file=/index.html

Thanks 🙏

**Comment by atomiks** [comment]
We have now released [Floating UI v1](https://floating-ui.com/docs/motivation), the successor to Popper.

Don't worry, Popper 2 will **continue to receive new releases** with bug/security fixes provided by external contributors, but development of new features is not continuing at this point. We are also closing bugs related to it as us maintainers are focusing our energy on tracking issues with Floating UI, however you are welcome to create new pull requests to fix bugs in Popper, which we will review and merge, as many packages (such as MUI, Bootstrap, etc) still rely on it. 

[This issue has been fixed in Floating UI](https://codesandbox.io/s/objective-drake-m9vfz6?file=/src/index.js), but you are welcome to create a new PR to fix it in Popper as well.

Thanks!
