### ISSUE TITLE
[React] Descendants `useList` API for navigation/typeahead

### ISSUE THREAD

**Issue by Marsony** [floating-ui/floating-ui#2235]
Hello everyone! Thanks for this great package.

Is it possible to add a possibility of using Record<string, HTMLElement> in listRef (useListNavigation) ?

In come cases we can't access children, so, we can't make an index number for each  of our options.
Our items can also be nested at different nesting levels (Select->Option or Select->Group->Option and etc)

Maybe applying of Record<useId(), HTMLElement> can solve this case?
https://github.com/floating-ui/floating-ui/discussions/2234 discussion

**Comment by atomiks** [comment]
The main question here is how do we know what index we are at with this (e.g. first/last index for initial focus and looping)?

**Comment by atomiks** [comment]
The README here is a good write-up of this problem: https://www.npmjs.com/package/@reach/descendants

**Comment by Marsony** [comment]
> The README here is a good write-up of this problem: https://www.npmjs.com/package/@reach/descendants

Yep, I was wrong.
It's too bad idea to make it on the low-level (floating-ui level).
Good solution for this (one of variants) is simple transform under hood of the root component (includes, indexOf, optionIndex.current with zeroing).

Option.tsx:
`const index = listValues.includes(value) ? listValues.indexOf(value) : optionIndex.current++;`

**Comment by atomiks** [comment]
I think this is a missing primitive in React or something. I also found this https://www.npmjs.com/package/use-descendants. 

I suggested before we combine `useListNavigation` + `useTypeahead` into a new API like `useList`, that should avoid this problem by doing something like the above package (without the warnings it has?). It seems quite small.

**Comment by atomiks** [comment]
Here's an example of how to use the package: https://codesandbox.io/s/floating-ui-descendants-index-r7i3cb?file=/src/App.tsx

**Comment by pierreburel** [comment]
I stumbled into this issue writing a Listbox component with (optional) grouping, and i have to admit the `useDescendant` approach make it really easy. It also fixes an issue with `Children.map` not traversing fragments, that i fixed with [this method](https://www.npmjs.com/package/react-keyed-flatten-children) in the past.

It seems kind of fragile and experimental tho, but I found out that [Chakra UI](https://github.com/chakra-ui/chakra-ui/tree/main/packages/components/descendant) and even Volvo use this in [their Design System](https://vcc-ui.vercel.app/docs/packages/react-descendants).

Also, [use-descendants](https://www.npmjs.com/package/use-descendants) is not open source ([or is it?](https://github.com/pacocoursey/use-descendants)) and doesn't have typing.

Any chance you built this into Floating UI (before a potential rewrite as `useList`)?

**Comment by atomiks** [comment]
Yeah the plan is to incorporate this into Floating UI itself. The example with `use-descendants` was just to show the library can now work with packages like this (since 0.22), as before there were some issues.

**Comment by atomiks** [comment]
I have something working, but I don't think there's a way to allow the list components (`<Option>`) to be memoized at all, since `activeIndex` is passed in through context and compared inside the component. This isn't that huge of a deal if you use virtualisation, but then I wonder what the best API is for virtualization while retaining composition, e.g.  using the index from `rowVirtualizer.getVirtualItems().map` in `react-virtual`?

**Comment by atomiks** [comment]
Closing, as `FloatingList` released a few weeks ago, and I don't think you can achieve children composition with virtualization. I think it's easy enough to create component APIs like this now.
