### ISSUE TITLE
Tooltips on IOS PWA don't appear

### ISSUE THREAD

**Issue by glensargent** [floating-ui/floating-ui#2263]
**Describe the bug**
Tooltips don't show on IOS PWA, but work fine on Safari. Usually to trigger a tooltip on mobile browser you have to tap and then it'll appear, this however doesn't seem to work when trying via a PWA on IOS. To reiterate, everything works as intended on Safari, just not their pwa webview.

**To Reproduce**
Click to view tooltip on ios pwa

Install app as a pwa on ios (add to homescreen)
Attempt to view a tooltip

**Expected behavior**
Tooltip should appear like it does on chrome / safari

**Context:**
 - OS: iOS
 - Browser: PWA WebView (Safari?)

**Comment by atomiks** [comment]
Do you have a repo to test? Does it work if you add a `mouseenter` and `focus` listener manually, instead of `useHover`?

```js
useEffect(() => {
  refs.domReference.current.addEventListener('mouseenter', () => {
    setOpen(true);
  });
  // + `focus`
}, []);
```

**Comment by atomiks** [comment]
Just made a quick Vite React repo with `vite-plugin-pwa` and deployed to Netlify, added to iOS (16.3) homescreen. The floating element shows when tapping the reference element as expected (`v0.22.2`).

There may be some other code you have causing an issue, and without a reproduction, this ticket isn't actionable atm.


https://user-images.githubusercontent.com/22450188/229262557-c798dda0-0270-4252-aff5-5b010f540551.MP4

<details>
  <summary>
  View config and App.jsx
  </summary>

```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), VitePWA()],
  server: {
    host: true,
  },
});
```

```js
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import { useFloating, useHover, useInteractions } from "@floating-ui/react";

function App() {
  const [isOpen, setIsOpen] = useState(false);

  const { x, y, refs, context } = useFloating({
    open: isOpen,
    onOpenChange: setIsOpen,
  });

  const hover = useHover(context);
  const interactions = useInteractions([hover]);

  return (
    <div className="App">
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <div ref={refs.setReference} {...interactions.getReferenceProps()}>
          Reference
        </div>
        {isOpen && (
          <div
            ref={refs.setFloating}
            style={{
              position: "absolute",
              top: y ?? 0,
              left: x ?? 0,
            }}
            {...interactions.getFloatingProps()}
          >
            Floating
          </div>
        )}
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </div>
  );
}

export default App;
```
</details>

I also added all the other relevant hooks (`dismiss`, `focus`, etc), and disabled `move` in `useHover` and it continues to work fine.

What _might_ be the problem, I noticed, is that `pointerdown` dismissal (e.g. when touch-moving to scroll) won't allow `mouseenter` to fire again unless you explicitly tapped somewhere else. In this case, you can change `outsidePressEvent: 'mousedown'` in the `useDismiss` hook so the tooltip won't close unless there was an intentional tap to begin with. But it still works fine on the first open.
