### ISSUE TITLE
useTypeahead: string with `" "` in the typed string is not persisted and resets the string

### ISSUE THREAD

**Issue by lwkchan** [floating-ui/floating-ui#2304]
**Describe the bug**

Hello. Currently upgrading to @floating-ui/react 0.23.0. When using the typeahead to find a match in the list and when the list is _closed, the `" "` (space) character causes the typed string to reset.

This broke some of our previous tests, but I'm not sure whether this is an intentional trade-off. My thinking is there might need to be some communication between `useTypeahead` and `useListNavigation`, which opens the list.

Nonetheless, from testing the native select in the same way, I've found that the latest versions of Chrome and Firefox accept space character as a typed string and keep the list box closed. However, Safari's native select opens the list when space is used - similar to how the `useTypeahead` behaves now.

```html
<select name="options" id="options">
   <option value="" disabled selected>Select your option</option>
   <option value="1">Option 1</option>
   <option value="2">Option 2</option>
   <option value="3">Option 3</option>
   <option value="4">Option 4</option>
</select>
```

**To Reproduce**

https://codesandbox.io/s/blissful-tree-yzr9xn?file=/src/App.tsx 

1. With keyboard, `Tab` to focus on the select
2. Type on keyboard `"Option 2"`
3. Actual behaviour: The list opens and "Option 1" is highlighted in the list

**Expected behavior**
`"Option 2"` should be highlighted and the list should remain closed

**Screenshots**

Video: 

https://user-images.githubusercontent.com/8487313/234819889-b0c42a68-2623-418b-8707-4dae92406a68.mov

**Context:**
 - OS: MacOS
 - Browser Firefox 
 - Version 112

**Comment by atomiks** [comment]
The sandbox links to the template not the issue described

**Comment by lwkchan** [comment]
@atomiks Updated description to https://codesandbox.io/s/blissful-tree-yzr9xn?file=/src/App.tsx

**Comment by atomiks** [comment]
From what I can see, this has always been a bug (it's present in `v0.17.0` as well) when using a `<div>` instead of a `<button>` as the reference. (Safari VoiceOver has a bug when `button` has `role="combobox"` which is why the former `div` tag is used 🙄). 

The bug is because `useClick`, when attaching manual keyboard handlers to the `div`, does not check for `event.defaultPrevented`. If it were to, you'd need make sure `click` is placed after `typeahead` in the `useInteractions` array.  I will fix this but the order mattering is a caveat I suppose.

**Comment by lwkchan** [comment]
Thank you for this 🙏🏻 💯
