### ISSUE TITLE
Positioning issue when using fixed strategy within a new containing block (`filter: drop-shadow()`)

### ISSUE THREAD

**Issue by benoitgrelard** [floating-ui/floating-ui#2333]
When using `strategy: 'fixed'`, there is an issue with positioning when within a new containing block created by `filter`.

**To Reproduce**
- @floating-ui/dom: https://codesandbox.io/s/floating-ui-fixed-strategy-bug-f4hey0?file=/src/index.js

**Expected behavior**
Should be positioned correctly.

**Screenshots**
<img width="483" alt="CleanShot 2023-05-17 at 21 08 19@2x" src="https://github.com/floating-ui/floating-ui/assets/1539897/45f4f9fd-a1dd-41e1-8b65-61e9be4c58ad">

**Context:**
Looks like it's only an issue in Chrome.

**Additional context**
See https://github.com/radix-ui/primitives/issues/2018#issuecomment-1551243712

**Comment by atomiks** [comment]
It looks this bug is caused by a recent change in Chromium for determining if a node is a containing block. Previously, only Firefox created one when `filter` was specified, but now I guess Chrome does too (removing `isFirefox` fixes the issue):

https://github.com/floating-ui/floating-ui/blob/b8737712255909c5e890b5d68d1006d766439cec/packages/dom/src/utils/is.ts#L60

I'm not sure in which version this change happened...

**Comment by benoitgrelard** [comment]
Upstream fix: https://github.com/floating-ui/floating-ui/pull/2334
