### ISSUE TITLE
FloatingFocusManager cannot use a VirtualElement

### ISSUE THREAD

**Issue by obeattie** [floating-ui/floating-ui#2458]
**Describe the bug**
`FloatingFocusManager` seems expects the reference element given to `useFloating` to be a _real_ DOM element, and throws an exception when it isn't. However, it's my understanding from the [type signature of `useFloating`](https://github.com/floating-ui/floating-ui/blob/800298e46bd1ddee91bf02d52470dbbbd70eb855/packages/react-dom/src/types.ts#L76) and from [the documentation](https://floating-ui.com/docs/virtual-elements) that it should be possible to pass a virtual element to position the item at a particular point on-screen (eg. relative to a click). The `VirtualElement` type, however, does not include the `getAttribute` method that `FloatingFocusManager` expects.

**To Reproduce**

1. Go to https://codesandbox.io/s/floatingfocusmanager-virtualmanager-bug-38m6vr?file=/src/App.tsx
2. Click "Click me"
3. Observe the error

**Expected behavior**

No errors to be thrown.

**Context:**
 - OS: macOS
 - Browser: Chrome
 - Version: 114.0.5735.198 (Official Build) (arm64)

**Comment by atomiks** [comment]
In `react` (not `react-dom`), `refs.setPositionReference` should be used:

```js
  const { refs, floatingStyles, context } = useFloating({
    whileElementsMounted: autoUpdate,
    placement: "bottom-start"
  });

  useLayoutEffect(() => {
    refs.setPositionReference({
      getBoundingClientRect: () => ({
        width: 0,
        height: 0,
        x: 100,
        y: 100,
        top: 100,
        right: 100,
        bottom: 100,
        left: 100
      })
    })
  }, [refs]);
```

Since TS doesn't error though, it would be a type bug. Maybe an `elements.positionReference` option can be added as an alternative

**Comment by ACHP** [comment]
Hey @atomiks I know this issues has been fixed and closed like a year ago, but I was wondering if you would consider any PR _fixing_ the `FloatingFocusManager` instead of the `useFloating` react implementation ? Or maybe hide the `refs.setPositionReference` call inside  `useFloating` if we detect that this is a VirtualElement ?

I don't know `floating-ui` very much so maybe this would be a nonsense or very hard to do but I find it confusing that the `react-dom` implementation accept a **VirtualElement** as reference, but not the `react` one, especially if it is actually possible to make it work via another setter.

Also the documentation for [useFloating](https://floating-ui.com/docs/useFloating) specify that the type of reference is `ReferenceElement` and when we search it in the type definition we find `export type ReferenceElement = Element | VirtualElement;`. So it's even more confusing to find that actually the react implementation differs from the react-dom on this point.

I'm currently trying to create an abstraction based on floating-ui, to create context menu available anywhere on right-click **anf** when clicking on a specific menu, I think I can "hide" the `refs.setPositionReference` inside my component it feels a bit too much like a workaround.

Also, thanks for this library  🙏 👍
