### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by meri-maki** [floating-ui/floating-ui#2468]
Hi! I'm facing the ResizeObserver loop issue with "@floating-ui/react": "^0.24.8",
I'm using reusable tooltip component based on official example
https://codesandbox.io/s/xenodochial-grass-js3bo9?file=/src/App.tsx

I've set width of my tooltip to fixed via css, but could you please explain where should I put ```autoUpdate``` with ```elementResize: false```.. It's a bit unclear in docs how it should be used in react...

_Originally posted by @meri-maki in https://github.com/floating-ui/floating-ui/issues/1740#issuecomment-1656115591_

**Comment by atomiks** [comment]
> It's a bit unclear in docs how it should be used in react...

At the bottom of the [Anchoring section](https://floating-ui.com/docs/react#anchoring) it shows how to pass options. The `whileElementsMounted` prop is called with 3 arguments, matching `autoUpdate`'s signature.

Since there is no reproduction on this issue, it will be closed. Feel free to make one and I can re-open the issue.
