### ISSUE TITLE
The `VirtualElement` interface is missing the `getClientRects` method.

### ISSUE THREAD

**Issue by Flrande** [floating-ui/floating-ui#2469]
Is this document not updated timely? As far as I know, `inline()` requires `getClientRects`.

<img width="822" alt="image" src="https://github.com/floating-ui/floating-ui/assets/50035259/a8e10543-d8c4-4bb0-8e21-a37d4ba8aae8">

<img width="823" alt="image" src="https://github.com/floating-ui/floating-ui/assets/50035259/adf0e152-92d6-49e2-9501-c94c61297080">

<img width="811" alt="image" src="https://github.com/floating-ui/floating-ui/assets/50035259/7bccb549-2903-44c7-bd4d-f4e45de3ef23">

**Comment by atomiks** [comment]
I did have a PR open here https://github.com/floating-ui/floating-ui/pull/2224 but can't actually remember why it was closed. I think it was due to a potentially breaking change in the types due to `DOMRectList` and `Array<ClientRectObject>` being different? You can pass the object in without using the type assignment to `VirtualElement` though and it will still work (that's why closing it wasn't really bad).

**Comment by Flrande** [comment]
Great. Thank you for your explanation. :)

**Comment by Flrande** [comment]
By the way, I'd like to ask a question: How can I dynamically adjust the position of floating elements?🤔 For example, I'm tracking the user's selection to determine the position of the floating element, but for the same type of selection, the user's dragging direction may vary. I want the floating element to appear above the selection when the user drags upwards and below the selection when dragging downwards.

**Comment by atomiks** [comment]
Can track which direction the cursor is going on window `mousemove` and set `placement` based on that.
