### ISSUE TITLE
[React] Safari/Webkit focus returns with delay (in tree) and close new floating element

### ISSUE THREAD

**Issue by deviun** [floating-ui/floating-ui#2533]
Hello! Floating UI is so great, but after some release i'd found bug with returning focus to prev. reference element. 

See my example in CodeSandbox: https://codesandbox.io/s/floating-ui-safari-focus-bug-5gpsr5?file=/src/App.tsx

1. Click button to show floating island.
2. Click 1st inner button, after click 2nd button. 

In Chrome-like browsers focus stay in new floating island, but in webkit(safari, ios/browser) focus returns to prev. reference with delay and close new floating element. 

Checked for 25.4 react package.

**Comment by atomiks** [comment]
Seems like it started happening from v0.23.1+

**Comment by atomiks** [comment]
I investigated this and it's due to the `focusout` handler having a different `relatedTarget` in this scenario in Chrome vs. Safari. In Safari, the code thinks it's an "unrelated" target (which is the button reference of the first popover), while in Chrome, it seems that the `relatedTarget` is the new popover that opens. This is possibly due to the fact that buttons don't receive focus when pressing them with a mouse in Safari.

A workaround is to conditionally change `closeOnFocusOut` for `FloatingFocusManager` temporarily (maybe if `pointerdown` was detected previously) for Safari.

**Comment by dbousamra** [comment]
Any further updates on this? Causing us a bit of grief.

**Comment by atomiks** [comment]
Haven't looked into a solution yet but there are 2 workarounds listed above.

**Comment by dbousamra** [comment]
Yep, I've used the "div + tabIndex={0}" approach, but it is a bit of a hack. Works for now though

**Comment by atomiks** [comment]
Somehow it seems like this is fixed already in `v0.26.4` 🤔 (using latest v17 Safari - not sure if that makes a difference, but the bug occurs in v0.25.4 using it.)

**Comment by dbousamra** [comment]
My tabIndex={0} approach stopped working all of a sudden
