### ISSUE TITLE
jest - getting console.error logged when using enableFloatingUIFocus option

### ISSUE THREAD

**Issue by smellai** [floating-ui/floating-ui#2534]
**Describe the bug**
If I define a test for a component using `enableFloatingUIFocus`, I get the following error logged:

```
console.error
    aria-hidden <ref *1> HTMLDivElement {
      '__reactFiber$mtphqclcq1c': <ref *2> FiberNode {
        tag: 5,
        key: null,
        elementType: 'div',
        type: 'div',
        stateNode: [Circular *1],
        return: FiberNode {
          tag: 0,
          key: null,
          elementType: [Function: FloatingFocusManager],
          type: [Function: FloatingFocusManager],
          stateNode: null,
          return: [FiberNode],
          child: [FiberNode],`
          
           [...]

          }
    } in not contained inside HTMLBodyElement {} . Doing nothing
```

**To Reproduce**
```
it.('should show popup properly', () => {
    const { baseElement } = render(
      <Popover>
        <button>Click me</button>
      </Popover>
    );

    expect(baseElement).toMatchSnapshot();
  });
```

**Context:**
 - OS: MacOS
 - Browser: jsdom

**Comment by atomiks** [comment]
I don't know what `enableFloatingUIFocus` is, as this library has no such term anywhere in it. The reproduction linked also contains no code to be able to help at all. 

Regardless, with the latest `@floating-ui/react` installed, this error doesn't appear since it uses a custom version of the `aria-hidden` package now without that error.

Issues without a proper reproduction are closed though, if you provide one that shows a legitimate problem it can be re-opened, thanks 🙏

**Comment by smellai** [comment]
Sorry, it was a flag passed to enable `<FocusManager>`

I confirm I don't see the error anymore with version 0.25, thanks!
