### ISSUE TITLE
Reference gets clipped even when using `shift()` if `arrow()` is used as well.

### ISSUE THREAD

**Issue by mattbryson** [floating-ui/floating-ui#2549]
**Describe the bug**
When trying to show a tooltip on an reference element , if the floating element is going to be clipped we can use `shift()` to ensure its on screen.

However, if a `arrow()` with padding is used, the reference is clipped off screen as it is aligned to the arrow.

**To Reproduce**
https://codesandbox.io/s/spring-firefly-tyzqkx?file=/src/index.js

**Steps to reproduce the behavior:**
View the example above, one shows it with `arrow()` and one without.

**Expected behavior**
Would it not make more sense to shift the reference into view with the arrow and the set the arrow middleware to indicate the [centerOffset](https://floating-ui.com/docs/arrow#centeroffset) Allowing the dev to hide or change the arrow?

**Screenshots**
<img width="624" alt="Screenshot 2023-09-13 at 16 50 53" src="https://github.com/floating-ui/floating-ui/assets/548948/72b0417f-dbaa-4837-af62-6a60dfbc3f0e">

**Context:**
 - OS: macOS
 - Browser Brave
 - Version 1.56

**Additional context**
You can add `shift()` after `arrow()` but then you loose a lot of the clever positioning of the arrow.

**Comment by atomiks** [comment]
> Would it not make more sense to shift the reference into view with the arrow and the set the arrow middleware to indicate the [centerOffset](https://floating-ui.com/docs/arrow#centeroffset) Allowing the dev to hide or change the arrow?

Shifting the reference is possible using the `centerOffset` data, but the reference usually is static, as that would cause its layout to shift which is usually undesirable. 

The `centerOffset` value allows you to implement skewing to make it point toward the reference in scenarios like this: https://github.com/floating-ui/floating-ui/pull/2423

Context on the current behavior of the arrow: https://github.com/floating-ui/floating-ui/pull/1496 - essentially, the floating element will shift itself from a true `end` alignment so that the arrow appears centered. This is okay when the reference is small but not when it's at the edge of a container. In this case, it causes the floating element to overflow as a side effect.

Placing a duplicate `shift()` at the end is indeed a way to opt out of the current behavior as you mentioned. It doesn't lose the clever positioning of the arrow though, it just prevents the arrow from causing the floating element to be clipped (and point toward empty space since the arrow isn't allowed to overflow the floating element itself).  The `centerOffset` value then allows you to hide or skew the arrow when it can't stay centered in this scenario.

**Comment by mattbryson** [comment]
@atomiks Yes - makes sense.

I mistyped when I said shift the reference into view, I meant shift the floating element into view!

I didn't realise you could run the the `shift()` middleware twice.  That very nearly solves the issue.

The one thing I still have though is that the `centerOffset` value is 0, even though the arrow is NOT pointing at the centre of the element due to the `shift()`.

Ive updated the sandbox to shift the floating element into view and log the `centerOffset` to the console....

https://codesandbox.io/s/spring-firefly-tyzqkx?file=/src/index.js

**Comment by atomiks** [comment]
Good spot, that is a bug. I think I found an easy solution for this problem regarding arrow's internal shifting + `shift()` and have made a PR. With the fix, you no longer need to add a second duplicate `shift()` after `arrow()`, and this allows the `centerOffset` value to continue to be correct.

**Comment by mattbryson** [comment]
wow - super fast 🥇  Ill check out the pr later.

**Comment by atomiks** [comment]
I notice now once it's in the "internal" shifting mode (only at the edge with arrow padding specified), and `flip()` is also in the array, it now flips to the opposite side unexpectedly at certain positions (after `reset` was added to `arrow()`). Re-opening as I'm aware of this problem and looking into a fix.

**Comment by atomiks** [comment]
^ Above problem should also be fixed in new installs (picking up `@floating-ui/core@1.5.0` once it's released)
