### ISSUE TITLE
[React] More details from `useDismiss` hook.

### ISSUE THREAD

**Issue by R-Bower** [floating-ui/floating-ui#2577]
**Is your feature request related to a problem? Please describe.**
I'm building a complex overlay panel with controlled/uncontrolled state.  The custom `onChange` property for these components features a `reason` parameter.  Currently, it's difficult to determine which action triggered the close (e.g. `outside-press` , `reference-press`, or `escape`), and this context is useful to my consumers.

**Describe the solution you'd like**
A callback function from `onDismiss` that fires with the DOM Event and name of the event that triggered the close:

```typescript
closed(event: Event, reason: 'outside-press' | 'reference-press' | 'escape-key'): void
```

**Describe alternatives you've considered**
None

**Comment by atomiks** [comment]
So this is actually done internally via the `context.events` emitter (`context.events.on('dismiss', payload => {})`, however it's not documented and not really a great solution for external use because of the magic strings.

I'm currently looking into adding an `onDismiss` callback as an option to the hook that receives a similar payload.

**Comment by atomiks** [comment]
I believe that an alternative API may be better, because you may also want details from other hooks. 

Here's what I'm thinking:

`onOpenChange` already provides the event that caused the open state to change via the second parameter:

```js
onOpenChange(open: boolean, event?: Event)
```

What if we just added more details to this hook, including `reason`?:

```js
onOpenChange(
  open: boolean, 
  event?: Event & {reason: string} // actually a string literal union
)
```

I'm not sure what structure to give the `reason` string though. One option could be to scope it like `hook:event-type`.

e.g., for `useDismiss`:

```js
useFloating({
  onOpenChange(open, {reason}) {
    // reason === 'dismiss:escape-key'
    // reason === 'dismiss:outside-press'
  }
});
```

Or for `useHover`:

```js
useFloating({
  onOpenChange(open, {reason}) {
    // reason === 'hover:entered-reference'
    // reason === 'hover:left-reference'
    // reason === 'hover:left-safe-polygon'
  }
});
```

The last string there I was already considering: 

https://github.com/floating-ui/floating-ui/blob/0668ed61a2a12481a97b7d332f16cf61e5fb87ac/packages/react/src/hooks/useHover.ts#L248-L252
