### ISSUE TITLE
[DOM] Adding an arrow padding alters the offset of the floating element.

### ISSUE THREAD

**Issue by ValJed** [floating-ui/floating-ui#2641]
I might do something wrong here but when adding a padding to my arrow I realize that the offset of the floating element is modified (increased).
So it appears when I have a `bottom-end` placement, when `middlewareData.arrow` has a positive centerOffset, but in my case there is no reason why the arrow couldn't be centered to the reference element.

I  also saw the same behavior with an `alignmentOffset` and not a `centerOffset`.

**To Reproduce**

To show you here is how it looks like with this config:
```javascript
    placement: 'bottom-end',
    middleware: [
      offset(11),
      shift({ padding: 5 }),
      flip(),
      arrow({
        element: arrowEl.value
      })
    ]
```
![image](https://github.com/floating-ui/floating-ui/assets/17548370/61eab281-f557-4068-98e8-1c132fee96b5)

If I just add a padding to the arrow here like so:
```javascript
    placement: 'bottom-end',
    middleware: [
      offset(11),
      shift({ padding: 5 }),
      flip(),
      arrow({
        element: arrowEl.value,
        padding: 5
      })
    ]
```
![image](https://github.com/floating-ui/floating-ui/assets/17548370/375bc56c-72b9-4b22-9aa9-cce6c7ea3678)

As you can see the offset of the floating element has changed whereas there is no collision.

Maybe it needs some computation from my end here but I don't feel it should behave like that.

I'm sorry I tried to make a codesandbox to make it more clear for you but I get an error when importing `arrow` from `@floating-ui/dom`, whereas I updated `@floating-ui/dom` to the latest version..

**Expected behavior**

Adding a padding to an arrow should not alter the offset of the floating element.

Thanks a lot for your clarifications.

**Context:**

- OS: Arch
- Browser Firefox
- Version 1.5.3

**Comment by atomiks** [comment]
The floating element's alignment axis coordinate can get adjusted if the arrow can't point toward the center with a perfect edge alignment, but not the side axis coordinate. 

I don't know why the main/side axis offset increases in your example, and I can't see the actual bounding box of the reference element in your screenshots. A reproduction is necessary here (maybe try Stackblitz instead of CodeSandbox).

To be clear, the code that changes the floating element's alignment offset is here:

https://github.com/floating-ui/floating-ui/blob/fbc2cb170caa85f9931d8b432f61b102a2c4edc1/packages/core/src/middleware/arrow.ts#L108

But `axis = getAlignmentAxis(placement)`, which should never cause the side offset to change.

**Comment by ValJed** [comment]
Thank you for this quick fix!!
