### ISSUE TITLE
Vue HeadlessUI + FloatingUI: Failed to execute 'getComputedStyle' on 'Window'

### ISSUE THREAD

**Issue by pbrzosko** [floating-ui/floating-ui#2691]
**Describe the bug** 

When using Vue version, I get the following errors:

```
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at getComputedStyle (floating-ui.dom.umd.js:87:31)
    at isOverflowElement (floating-ui.dom.umd.js:55:9)
    at getOverflowAncestors (floating-ui.dom.umd.js:138:57)
    at autoUpdate (floating-ui.dom.umd.js:655:121)
    at attach (floating-ui.vue.umd.js:141:39)
    at callWithErrorHandling (vue.esm-browser.js:1663:22)
    at callWithAsyncErrorHandling (vue.esm-browser.js:1673:21)
    at job (vue.esm-browser.js:3085:17)
    at resetScheduling (vue.esm-browser.js:594:38)
    at triggerEffects (vue.esm-browser.js:638:5)
```

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'defaultView')
    at getDPR (floating-ui.vue.umd.js:38:39)
    at roundByDPR (floating-ui.vue.umd.js:43:17)
    at eval (floating-ui.vue.umd.js:93:20)
    at ReactiveEffect.eval [as fn] (vue.esm-browser.js:1257:48)
    at ReactiveEffect.run (vue.esm-browser.js:507:25)
    at get value [as value] (vue.esm-browser.js:1266:67)
    at triggerComputed (vue.esm-browser.js:528:21)
    at get dirty [as dirty] (vue.esm-browser.js:481:21)
    at instance.update (vue.esm-browser.js:6694:24)
    at callWithErrorHandling (vue.esm-browser.js:1663:36)
```

**To Reproduce**

https://stackblitz.com/edit/vue-tzedys?file=src%2Fcomponents%2FHelloWorld.vue

1. Run the project
2. Inspect console errors

**Expected behavior** 

Project should run without issues.

**Screenshots** 

![image](https://github.com/floating-ui/floating-ui/assets/67122459/c3014a68-dcb4-41f5-b153-1e47472d676f)

**Context:**

- OS: iOS
- Browser chrome
- Version 120

**Additional context**

I am using custom components for both reference and floating. Maybe that is the issue? Looking at the code, it seems like computed proprety returning floating element {el: _, $el: _} is passed to a function as HTML element?

**Comment by atomiks** [comment]
Watching the value of `reference`/`floating`, it's a `Proxy`, not an `HTMLElement`. TypeScript maybe would've surfaced an error here? 

Replacing `ListboxButton` and `ListboxOptions` with a `<div>` prevents the issue. I don't know how `@headlessui/vue` is assigning the ref values here but it doesn't match native elements? (Note: not a Vue user - @lozinsky)

**Comment by pbrzosko** [comment]
According to the docs it should work with custom elements: https://floating-ui.com/docs/vue#custom-components

**Comment by lozinsky** [comment]
The `useFloating` tries to [unwrap](https://github.com/floating-ui/floating-ui/blob/master/packages/vue/src/utils/unwrapElement.ts) an element if `$el` property exists, as `vueuse` [does](https://github.com/vueuse/vueuse/blob/main/packages/core/unrefElement/index.ts). But since `unwrapElement` fallbacks to original value if `$el` is null, we have this behaviour. I'll figure out how to fix it.

You can use this workaround right now:

```js
const { floatingStyles } = useFloating(reference, computed(() => floating.value?.$el ?? null), {
  whileElementsMounted: autoUpdate,
});
```

**Comment by pbrzosko** [comment]
Yep, I just noticed that on the headless ui playground: https://github.com/tailwindlabs/headlessui/blob/main/playgrounds/vue/src/components/menu/menu-with-floating-ui.vue

**Comment by mediafreakch** [comment]
I run into the same issue with `@floating-ui/vue@1.0.3`. But only in the production build. During development it worked as expected. Using a computed value for the floating element fixed the issue. Floating element in my case was a Vuetify VCard component.

**Comment by lozinsky** [comment]
Oh, it looks like this function is returning `false` in production mode.

```ts
function isComponentPublicInstance(target: unknown): target is ComponentPublicInstance {
  return target != null && {}.hasOwnProperty.call(target, '$el');
}
```

I tried to replace `hasOwnProperty` condition with `in` operator and it works fine.

```ts
function isComponentPublicInstance(target: unknown): target is ComponentPublicInstance {
  return target != null && typeof target === 'object' && '$el' in target;
}
```

This is because Vue component proxy doesn't have [object property descriptors](https://github.com/vuejs/core/blob/07922dacc7422e828eb4238eac58dd11cd2cdb5c/packages/runtime-core/src/componentPublicInstance.ts#L552-L559) in production mode. But it has `has` [handler](https://github.com/vuejs/core/blob/07922dacc7422e828eb4238eac58dd11cd2cdb5c/packages/runtime-core/src/componentPublicInstance.ts#L468-L484) that is a trap for the `in` operator.
