### ISSUE TITLE
Whenever core/dom/utils/etc packages update the framework packages (i.e. vue/react) should also update

### ISSUE THREAD

**Issue by jonathan-rvezy** [floating-ui/floating-ui#2710]
**Is your feature request related to a problem? Please describe.**
Whenever dom/core (or other related dependencies are updated), the framework packages do not receive the benefit of this updates unless the dependencies are updated as well. The problem that was observed by this was the most recent update from vue@1.0.2 => vue@1.0.3 the floating elements were no longer positioned correctly. Since it was a "patch" update we thought it was safe to update, but it indeed was not because something changed beyond the scope of a patch release.

**Describe the solution you'd like** 
Any time the dependencies are changed from this project (dom/core/utils/etc), a corresponding framework release package should be released so that incremental updates can be realized and as well correctly SEMVER. In this particular case 1.0.3 should have probably become 1.1.0 or even 2.0.0 since it introduced breaking changes.

**Describe alternatives you've considered** 
Rolled back to the previous version as we're not prepared to investigate why it's broken.

**Comment by atomiks** [comment]
`@floating-ui/vue@1.0.3` did receive all the dependency updates simultaneously though, so if you upgraded to it, all the dependencies also updated.  A potential breakage in the Vue package isn't related to dependencies since they're all backwards-compatible (and abide by `^` semver range, which allows new installs to pick up the latest versions), nor do we break things between patches intentionally.

> Rolled back to the previous version as we're not prepared to investigate why it's broken.

If you found something broke when updating, please make a reproduction along with your issue. As it stands,  there's nothing to act on here because the Vue library does have tests for various use cases, but for some reason however you're using it clearly broke.

Here's the PR of the Vue-specific changes if you do end up finding the time to investigate: https://github.com/floating-ui/floating-ui/pull/2697

**Comment by jonathan-rvezy** [comment]
The problem isn't with the vue update itself, but rather the dependencies (which are all part of this project) has introduced some kind of breakage. The [diff between 1.0.2 & 1.0.3](https://github.com/floating-ui/floating-ui/compare/%40floating-ui/vue%401.0.2...%40floating-ui/vue%401.0.3) is HUGE, I don't have time to 165 commits or 518 files to figure out what actually broke. 

There's a lot more than just "dependency" updates based off the diff.

**Comment by atomiks** [comment]
Yes, many of those are docs and React-package related, which won't affect your usage with the Vue package. The only thing that changed in the Vue package (runtime wise) since v1.0.2 is that PR I linked. 

What you're suggesting is that either the `core`, `dom`, or `utils` package update broke something for you instead. You don't need to trawl through 165 commits; you can try isolating the issue based purely on the versions you have. For example, you could try pinning the dependency versions to their previous version you had (and listing them out here from your lockfile) while updating `@floating-ui/vue` alone. You could try changing the versions of the dependencies incrementally to see which one introduced the issue. If it's broken with the previous pinned dependencies but the latest Vue package, then that PR linked is the sole cause.

We can't magically fix the issue without some help, because we don't see any problems. Keep in mind too, that we haven't had any issues (yet) about positioning from users of other packages which also use the dependencies, which means the Vue package change alone is possibly more likely/suspicious.
