### ISSUE TITLE
useFocus: floating element does not disappear if it has focusable children and you blur by tabbing

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [floating-ui/floating-ui#2760]
**Describe the bug** 

When using the `useFocus` hook with a focusable reference element and a floating element with a focusable child, the floating element does not hide itself when you blur the child by tabbing forward or backward.

Video demo:

https://github.com/floating-ui/floating-ui/assets/19352442/618ea487-9faa-45d3-a7df-dedef9f016dc

**To Reproduce**

Minimal repro case + contrasting example without a focusable child: https://codesandbox.io/p/sandbox/floating-ui-react-bug-where-poppers-dont-disappear-on-blur-kqpkjy?file=%2Fsrc%2FApp.tsx%3A73%2C37

Instructions are provided in the sandbox on how to repro, but basically:

1. Follow the docs on `useFocus`: https://floating-ui.com/docs/useFocus
2. Edit the floating element to render a focusable child, like a button.
3. Tab forward through the reference and floating element. Observe that the floating element lingers on blur once focus leaves the nested focusable child of the floating element.

**Notably**, this is only reproducible when blurring via keyboard nav. Blurring via click behaves as expected in the first demo.

**Expected behavior** Floating elements should hide on blur.

**Context:**

- OS: macOS
- Browser: Chrome 
- Version: 120.0.6099.234 (Official Build) (x86_64)

**Comment by atomiks** [comment]
This is because `useFocus` doesn't add `focusout` listeners to the floating element itself, and only listens for the reference blurring, which doesn't happen in this scenario. 

`FloatingFocusManager` however does with non-modal focus management:

```js
<FloatingFocusManager context={context} modal={false} initialFocus={-1}>
  {/* floating element */}
</FloatingFocusManager>
```

In general, it's better to use the focus manager for this because it also handles portaled floating elements which the above Sandbox doesn't (if there were to be focusable elements between the reference and floating element in the DOM tree)

https://codesandbox.io/p/sandbox/floating-ui-react-bug-where-poppers-dont-disappear-on-blur-forked-zz9w8k?file=%2Fsrc%2FApp.tsx%3A33%2C19

**Comment by AleksandrHovhannisyan** [comment]
@atomiks Gotcha, thanks for clarifying! That fork does what I need.

I think it might be helpful to mention `FloatingFocusManager` in the docs for `useFocus` to clarify that it's more suitable in situations where the floating element is focusable. We can close this issue, though.
