### ISSUE TITLE
`autoUpdate` calls `updatePosition` continuously when the floating element is clipped by a parent with overflow hidden.

### ISSUE THREAD

**Issue by mattbryson** [floating-ui/floating-ui#2831]
**Describe the bug** 
`autoUpdate` calls `updatePosition` continuously when the floating element is clipped by a parent with overflow hidden.

At first it is fine, but after a scroll event it will fire every 100ms until the element is no longer being clipped.

Appears to be related to `IntersectionObserver` not detecting the intersection and then floating ui calls its `observeMove` `refresh` method continuously as the intersection ratio is 0 when its clipped.

Not sure if there is a way to handle this so it doest continuously call `updatePosition`

**To Reproduce**

https://codesandbox.io/p/sandbox/floating-ui-dom-template-forked-snsfn2?file=%2Findex.html%3A12%2C1

1. Go to [sandbox](https://codesandbox.io/p/sandbox/floating-ui-dom-template-forked-snsfn2?file=%2Findex.html%3A12%2C1)'
2. Click on 'Collapse Container'
3. Scroll the page
4. See the count of times `updatePosition` continuously fires

**Expected behavior** 
`updatePosition` is only fired when the position needs to be updated, even when the item is hidden due to parent clipping

**Screenshots** If applicable, add screenshots to help explain your problem.

**Context:**

- OS:  macos
- Browser Brave
- Version  1.63.169 Chromium: 122.0.6261.111 (Official Build) (arm64)

**Additional context**

**Comment by atomiks** [comment]
I'm aware of this loop, and internally the updates are throttled to 1 update per 100ms as you see. 

I didn't manage to find a way to fix it (there may be), but regardless of it, I didn't consider it to be a major issue once I throttled it, because the updates are still slower than those when scrolling, resizing, etc. In addition, it's also not common to have a floating element be mounted while clipped for extended periods, where the idle state having updates being called for a long period is a problem. No perf issues have been filed as an issue in the ~6 months since the feature was released.

The `layoutShift: boolean` option in `autoUpdate` can be set to `false` to prevent this from happening if absolutely necessary.

**Comment by mattbryson** [comment]
Yeah  - our use case is certainly on the edge!   We are injecting elements into existing sites, and need to account for when a elements parent is a collapse for example.    I did play with `layoutShift` but we ideally want that on when the item is visible.

We might be able to do something with the `detectOverflow` middleware - is there anyway to disable the `layoutShift` option on the fly?  

Ill keep playing and see what we can do.

**Comment by atomiks** [comment]
> We might be able to do something with the detectOverflow middleware - is there anyway to disable the layoutShift option on the fly?

Hmm interesting, I think using `hide()` can work indeed, by checking `referenceHidden` and calling `cleanup()` and setting it up again with new options. 

Something like this may work:
```js
let cleanup = autoUpdate(ref, float, update);

function update() {
  computePosition(ref, float, { 
    middleware: [hide()] 
  }).then(data => {
    cleanup();
    cleanup = autoUpdate(ref, float, { 
      layoutShift: !data.middlewareData.hide?.referenceHidden 
    });
  });
}
```

**Comment by mattbryson** [comment]
Yeah - Like it.  Agree with removing it  - we are doing a lot of that already so that fits nicely with how the app works atm.  Cheers for you help
