### ISSUE TITLE
useDismiss not working when click on iframe elements

### ISSUE THREAD

**Issue by WoodenPC** [floating-ui/floating-ui#2839]
**Describe the bug** I have popover component, similar to example component in docs. The component has useDismiss hook to handle outside clicks and close popover. On a page i have iframe element with some html inside. After opening popover and clicking on iframe content, popover not closing;

**Expected behavior** useDismiss working after click on iframe

"@floating-ui/core": "1.5.2",
"@floating-ui/react": "0.26.4",
"@floating-ui/react-dom": "2.0.4"

**Comment by atomiks** [comment]
The problem is the click occurs inside the iframe and the event doesn't bubble up to the main document listener, so it can't detect it. One solution is to use `FloatingOverlay`, so clicks are always detected on it as it covers the iframe, or make an element that overlays only the iframe while the popover is open to allow the click to be detected.
