### ISSUE TITLE
React Select component example not working in native dialog

### ISSUE THREAD

**Issue by bencoates08** [floating-ui/floating-ui#2931]
**Describe the bug** A clear and concise description of what the bug is.

Hi there!

The [React Select component example](https://codesandbox.io/s/gallant-sea-rcg43b?file=/src/Select.tsx) does not work when used within a native dialog component that has been opened with `showModal()` due to it's use of #top-layer.

**To Reproduce**

See the following [CodeSanbox](https://codesandbox.io/p/sandbox/fervent-cdn-ffy34k) (just the Select example within a dialog).

Steps to reproduce the behaviour:

1. Use the provided React Select Component within a native dialog element

**Expected behavior** A clear and concise description of what you expected to
happen.

The select dropdown menu should not be covered by the dialog element

**Screenshots** If applicable, add screenshots to help explain your problem.
<img width="529" alt="Screenshot 2024-06-13 at 11 38 36" src="https://github.com/floating-ui/floating-ui/assets/78369367/7ce4c941-74d4-4e26-a5a9-03f4ab5df47d">

**Context:**

- OS: iOS
- Browser Chrome
- Version 124.0.6367.202 (Official Build) (arm64)

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
You can either render the select component inside the dialog element itself, or use `<FloatingPortal root={dialogNode}>`, which will append the portal inside the top-layer dialog element.

**Comment by bencoates08** [comment]
Hey, thank you for the response!

Using `<FloatingPortal root={dialogNode}>` fixes the issue but isn't ideal from a reusability of the Select component point of view. I don't understand exactly what you mean by render the select component inside the dialog element itself?

Would appreciate any advice you have on the matter

**Comment by atomiks** [comment]
I mean you can remove the portal since the select is in the top layer already. 

If you have elements within the dialog that can clip it potentially, and the select is a child, then portaling to the dialog's root is still the most robust technically - but as you mention it's not great for reusability and would require some kind of context for the native dialog component to make it more ergonomic so it can automatically do it for the consumer using the JSX. 

But in most cases, not using a portal probably works fine while using the native dialog or other top layer elements.

**Comment by bencoates08** [comment]
Ah okay, I got you!

Some interesting options to chose from there, thank you for taking the time to respond!
