### ISSUE TITLE
Hide Middleware Not Hiding Panel When Reference Element Off-Screen (Shadow DOM Components)

### ISSUE THREAD

**Issue by ChellappanRajan** [floating-ui/floating-ui#2940]
**Describe the bug** 

  We have developed custom modal, drawer, and datepicker components as web components using ShadowDOM. These components utilize the popover attribute and floating-ui internally for datepicker positioning. However, the hide middleware is not hiding the panel when the reference element is off the screen

**CodeSandboxes:**

[Stackblitz URL](https://stackblitz.com/edit/vitejs-vite-jzzg6c?file=src%2Fdrawer.ts)

[Example](https://vitejsvitejzzg6c-drf5--5173--dc4d7514.local-credentialless.webcontainer.io/)

To see the issue:

1. Click the "show drawer" button to open a new drawer on the left side.

2. Scroll the container until the input field is visible click the input field which will open panel now Scroll the container until the panel is partially or completely off-screen

3. Observe that the datepicker panel remains visible even though the input field is off-screen.

**Context:**

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
To be honest I don't really understand this example but I think I know what's wrong.

1. You need to make sure you're enabling anchoring of the floating element using [`autoUpdate`](https://floating-ui.com/docs/autoUpdate). This allows the `hide()` `referenceHidden` calculation to be computed when scrolling. However there is still a problem with it not working due to 2):
2. The parent container's layout box (colored with cyan) seems to be larger than its visual box. The layout box is what is used to determine clipping, so it's not actually "hidden" according to the code.

<img width="312" alt="Screenshot 2024-06-22 at 4 04 06 PM" src="https://github.com/floating-ui/floating-ui/assets/22450188/d6fffdc6-aed7-4f50-aa64-5db4fb8267bf">

**Comment by ChellappanRajan** [comment]
Sorry for the confusion. Let me try to create a clean repo.

**Comment by ChellappanRajan** [comment]
Can you check this example, I have updated with autoUpdate method:https://stackblitz.com/edit/vitejs-vite-wxlmv9?file=src%2Fpicker.ts

**Comment by atomiks** [comment]
You just need to remove `boundary: []` from `hide()`. It's not detecting the clipping ancestors of the `input` reference element due to this. (Remember, latest version fixed some issues that renders an empty boundary unnecessary)
