### ISSUE TITLE
Button in Popover getting focus visible on hover

### ISSUE THREAD

**Issue by shamelio** [floating-ui/floating-ui#2966]
**Describe the bug** 
When hovering popover trigger, popover with interactive element (button) is visible focus.

**To Reproduce**

1. Go to [sandbox](https://codesandbox.io/p/sandbox/floating-ui-react-dom-template-forked-75vqtl)
2. Hover trigger
3. The button inside the popover has a visible focus.

See that it's happing only after first page reload - when clicking on the trigger first and then hovering - the inside button doesn't get visible focus.

**Expected behavior** 
button get visible focus only via keyboard tabbing

**Screenshots** 
<img width="538" alt="image" src="https://github.com/floating-ui/floating-ui/assets/150127866/7565b821-5314-412c-bf19-bfdbcb693d2b">

**Context:**

The sandbox is using floating-ui official popover example ([Reusable popover component](https://codesandbox.io/s/distracted-swirles-jo1pvu?file=/src/App.tsx)) with only adding `useHover` interaction

**Comment by atomiks** [comment]
This is a bug with how browsers detect `:focus-visible`. Unless you use your pointer first before hovering, the browser will show the outline. 

Workarounds: 

- Use `initialFocus={refs.floating}` on `FloatingFocusManager` to focus the floating element instead of the button (and give it `outline: 0` or such). You could also conditionally disable the initial focus value (`initialFocus={-1}`) if [`hover`](https://floating-ui.com/docs/useFloating#onopenchange) is what triggered the floating element to open.
- Polyfill `:focus-visible` with JS to make it smarter and handle this case, which is probably the best and easiest option. Headless UI does this as well as `react-aria`, because the browser's default is bad
