### ISSUE TITLE
Incorrect Popover positioning at rotating in Browser DevTools

### ISSUE THREAD

**Issue by juandrepanther** [floating-ui/floating-ui#2972]
**Describe the bug** 

Using browser DevTools (using toggle device toolbar) on resize (small width values) and on rotating / tilting Popover has an incorrect positioning. 

Here is the [Video](https://github.com/floating-ui/floating-ui/assets/72308869/331f0d6a-93d7-4d89-8be8-b923edf86003)

**To Reproduce**

1. Go to [CodeSandBox](https://codesandbox.io/s/withered-shadow-ot38mm?file=/src/App.tsx&resolutionWidth=320&resolutionHeight=675) or from floating/ui official documentation [Basic Popover](https://floating-ui.com/docs/popover) example.
2. Open your browser DevTools
3. Click on the button to open the Popover
4. Resize the screen by reducing the width for example 270px
5. Click the rotation / tilting button twice and see the incorrect position.

**Expected behavior**

Expect to see previous correct position even after multiple rotations / tiltings

**Screenshots** 

Normal positioning before rotations
![resized_opened_popover_no_rotateted](https://github.com/floating-ui/floating-ui/assets/72308869/0137a52c-69c4-43b5-9f42-c207b9c03b0c)

Incorrect positioning after twice rotations
![rotateted_twice](https://github.com/floating-ui/floating-ui/assets/72308869/7a4aecda-bbe9-4c93-9645-d71cc7f8f311)

**Context:**

- OS: WIndows 10
- Browser Google Chrome 
- Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by atomiks** [comment]
How is it incorrect?

**Comment by kputninsif** [comment]
When open It doesn't always get repositioned correctly after the device is rotated, see 0:07 to 0:08 of video

**Comment by atomiks** [comment]
It looks like it's positioned correctly the whole time? What you're referring to seems to be the document's width which isn't related to the floating element's position. Since it was placed on the right initially with horizontal orientation, when tilting back to vertical orientation, it has that extra space initially caused by the floating element being larger than the available space. In this case DevTools' viewport doesn't correctly reset the width until you resize - which seems like a possible DevTools quirk more than anything?
