### ISSUE TITLE
[react] userHover in mobile stuck open after clicking floater

### ISSUE THREAD

**Issue by KutnerUri** [floating-ui/floating-ui#2991]
**Describe the bug**

When using `useHover()` in **mobile**, pressing the floater prevents the popper from closing!

**To Reproduce**

https://codesandbox.io/s/floating-ui-react-dom-template-forked-qkpdqt?file=/src/App.js

1. Open preview in a new tab, switch to mobile view.
2. Press on "my button" to open the popper
3. You can verify it is closable by pressing away
4. press on "my tooltip"
5. Press anywhere else in the screen
6. Popper stays open

**Expected behavior** Tooltip should close when dismissing, when using hover behavior and is in mobile.
(like it would do normally without clicking the floater)

**Screenshots**
![Screenshot 2024-07-28 at 14 00 26](https://github.com/user-attachments/assets/f0d3023a-7ac6-4570-b77a-4aebd4e09037)

**Context:**

- OS: MacOS 14.5
- Browser: Chrome 126
- Version: `"@floating-ui/react": "^0.26.20"`

Doesn't seem to be effected by `safePolygon()`

### Workaround
- close it manually when clicking on the floater
- `useDismiss({ outsidePress: true, referencePress: true })` still works (even though the 'hover close' event is missing)

**Comment by atomiks** [comment]
This makes sense when you think of how the events work on touch devices. The `mouseleave` event on the trigger no longer gets fired because it got "wasted" into the click when pressing the tooltip. If you tap off off the tooltip, there's no `mouseleave` event anymore, so you need `useDismiss` for that to work. Given `useDismiss` is pretty much always used I don't see this being a practical issue.
