### ISSUE TITLE
onClick doesn't work inside a React component within PopoverTrigger

### ISSUE THREAD

**Issue by alisakova** [floating-ui/floating-ui#2994]
If you create a React component (for example, a Button) with an onClick handler and place it inside a PopoverTrigger, the onClick won't work because PopoverTrigger's onClick overrides it.
There is a workaround for this: wrapping the Button in a div.
However, are there other workarounds to fix this? I want to avoid adding an extra wrapper around the PopoverTrigger.

**To Reproduce**
I edited the Reusable Popover example to reproduce the issue. I created a Button component with a handleClick function and placed it inside the PopoverTrigger.
https://codesandbox.io/p/sandbox/elastic-shirley-yxs43r?file=%2Fsrc%2FApp.tsx%3A29%2C25-29%2C32

1. Go to link
2. Click on "Hello" button
3. There is no alert after click

**Expected behavior** 
There should be an alert after click

**Comment by atomiks** [comment]
This is a function merging problem where your `Button` component needs to merge the event handlers so they both work simultaneously.

A fix would be:
```js
<button 
  ref={forwardRef} 
  {...props} 
  onClick={(e) => {
    handleClick(e);
    props.onClick(e);
  }}
>
  Hello
</button>
```

**Comment by atomiks** [comment]
It's just a requirement to create properly reusable, composable components that are as flexible as native elements like `<button>`. 

In the above example, `<Button onClick={() => {}}` doesn't work in your component unless you merge all incoming props with the internal ones, which otherwise prevents users from adding their own click logic externally. All reusable component libraries handle function merging to ensure such external props work, which is the same principle.
