### ISSUE TITLE
useTransitionStatus - open duration not applied

### ISSUE THREAD

**Issue by chortis** [floating-ui/floating-ui#3034]
When using `useTransitionStatus` with `isMounted`, the `open` duration property does not work as expected and is not applied.
`close` works as intended.

This behaviour ALSO happens if you simply use `duration: 300`, `close` works but `open` does not.

The `initial`, `open` statuses ARE being correctly applied so it just seems to be an issue with duration.

**To Reproduce**

1. Go to https://codesandbox.io/p/sandbox/3xzd63
2. Click on 'Reference Element'
3. See it opens immediately, even with a 5000ms 'open' duration set
4. Click 'Reference Element' button again, see 300ms 'close' duration is correctly applied

**Expected behavior** 

Floating element would take 5000ms before opening.

**Screenshots** If applicable, add screenshots to help explain your problem.

https://github.com/user-attachments/assets/16afb8c6-96dc-48a6-bf1e-cb44c481a777

**Context:**

- OS: Mac
- Browser Chrome
- Version @floating-ui/react@0.26.23 

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
I don't see anything wrong here?  The `duration` for the `open` state, unlike `close`, doesn't act like a `delay`. The `close` duration appears to act like a delay because it has to wait for the animation to finish before unmounting (no animation is present in the CodeSandbox). On the other hand, the `open` one doesn't need to wait for anything and can play the animation immediately. 

Also: I'm not sure the `open` option is even necessary to begin with in the API and can probably be ignored.

**Comment by chortis** [comment]
> I don't see anything wrong here? The `duration` for the `open` state, unlike `close`, doesn't act like a `delay`. The `close` duration appears to act like a delay because it has to wait for the animation to finish before unmounting (no animation is present in the CodeSandbox). On the other hand, the `open` one doesn't need to wait for anything and can play the animation immediately.
> 
> Also: I'm not sure the `open` option is even necessary to begin with in the API and can probably be ignored.

Ahhh ok, yes I definitely misunderstood the reason for the open/close. I have it doing what I want in my real use case. Thanks. Small suggestion I guess then would be to just remove the `open` option in the API. Thanks for the response.
